In [2]:
import numpy as np
import tensorflow as tf

In [3]:
learning_rate = 0.001
batch_size = 100
training_epochs = 15
nb_classes = 10

mnist = tf.keras.datasets.mnist

In [5]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalizing data
x_train, x_test = x_train / 255.0, x_test / 255.0

In [6]:
# change data shape
print(x_train.shape)   # (60000, 28, 28)
x_train = x_train.reshape(x_train.shape[0], x_train.shape[1] * x_train.shape[2])
x_test = x_test.reshape(x_test.shape[0], x_test.shape[1] * x_test.shape[2])

(60000, 28, 28)


In [7]:
# one-hot encoding 
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

In [9]:
print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [10]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units = 10, input_dim = 784, activation = 'softmax'))
tf.model.compile(loss = 'categorical_crossentropy', optimizer = tf.optimizers.Adam(0.001), metrics = ['acc'])
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                7850      
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [11]:
history = tf.model.fit(x_train, y_train, batch_size = batch_size, epochs = training_epochs)

Epoch 1/15
600/600 [==============================] - 3s 2ms/step - loss: 0.6303 - acc: 0.8396
Epoch 2/15
600/600 [==============================] - 1s 2ms/step - loss: 0.3465 - acc: 0.9047
Epoch 3/15
600/600 [==============================] - 1s 2ms/step - loss: 0.3098 - acc: 0.9146
Epoch 4/15
600/600 [==============================] - 1s 2ms/step - loss: 0.2925 - acc: 0.9183
Epoch 5/15
600/600 [==============================] - 1s 2ms/step - loss: 0.2817 - acc: 0.9215
Epoch 6/15
600/600 [==============================] - 1s 2ms/step - loss: 0.2747 - acc: 0.9238
Epoch 7/15
600/600 [==============================] - 1s 2ms/step - loss: 0.2695 - acc: 0.9248
Epoch 8/15
600/600 [==============================] - 1s 2ms/step - loss: 0.2653 - acc: 0.9262
Epoch 9/15
600/600 [==============================] - 1s 2ms/step - loss: 0.2621 - acc: 0.9274
Epoch 10/15
600/600 [==============================] - 1s 2ms/step - loss: 0.2594 - acc: 0.9276
Epoch 11/15
600/600 [============================

In [12]:
predictions = tf.model.predict(x_test)
print('Prediction: \n', predictions)

Prediction: 
 [[2.5661616e-06 1.1851207e-11 1.0390902e-05 ... 9.9407899e-01
  1.7217460e-05 3.2290828e-04]
 [3.0957305e-04 2.9871601e-06 9.9164575e-01 ... 2.6657313e-17
  4.7123947e-05 3.0396072e-14]
 [1.6620110e-06 9.7850251e-01 1.3583730e-02 ... 7.4088154e-04
  2.6773778e-03 2.0040605e-04]
 ...
 [9.4850900e-09 7.3150690e-09 4.8769662e-06 ... 9.4575289e-04
  4.2793844e-03 9.8217111e-03]
 [1.3982151e-07 2.2415188e-07 1.7643703e-07 ... 7.2381717e-08
  4.5731310e-03 7.3949103e-08]
 [1.1848924e-06 1.7733323e-14 4.6221034e-05 ... 2.4755211e-12
  2.8945863e-08 2.0071457e-11]]


In [13]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
score = tf.model.evaluate(x_train, y_train)
print('Accuracy: {}'.format(score[1]))

1875/1875 [==============================] - 3s 2ms/step - loss: 0.2461 - acc: 0.9322
Accuracy: 0.9321500062942505
