In [4]:
# !pip install IPython 

In [5]:
from IPython.display import Image

In [3]:
import numpy as np
import pandas as pd
np.__version__

'1.19.5'

# numPy 특징
    - Numerical Python의 약자
    - 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
    - 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
    - 정교한 브로드캐스팅(Broadcasting) 기능
    - 파이썬의 자료형list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
    - 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
    - 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

## 배열 생성

#### 리스트로 배열 만들기

![nn](0_y04Nh3L0aSwyGaby.png)

In [10]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [67]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 1], a2[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [68]:
a3 = np.array([[ [1, 2, 3], [4, 5, 6], [7, 8, 9] ],
              [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ],
             [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


#### 배열 생성 및 초기화

    - zeros() : 모든 요소를 0으로 초기화

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

    - ones() : 모든 요소를 1로 초기화

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

    - full() : 모든 요소를 지정한 값으로 초기화

In [19]:
np.full((3, 3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

    - eye() : 단위행렬(identity matrix) 생성
        * 주대가선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각행렬

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

       * tri(): 삼각행렬 생성

In [22]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

    - empty() : 초기화되지 않은 배열 생성
        * 초기화가 없어서 배열 생성비용 저렴하고 빠름
        * 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [23]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

    - _like() : 지정된 배열과 shape가 같은 행렬 생성
        * np.zeors_like()
        * np.ones_like()
        * np.full_like()
        * np.empty_like()

In [25]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [26]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

    - arange() : 정수 범위로 배열 생성

In [28]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

    - linspace() : 범위 내에서 균등 간격의 배열 생성

In [30]:
np.linspace(0, 1, 8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

    - logspace() : 범위 내에서 균등간격으로 로그스케일로 배열 생성

In [31]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성

    - random.random() : 랜덤한 수의 배열 생성

In [32]:
np.random.random((3, 3))

array([[0.94378263, 0.10886633, 0.08908873],
       [0.54589899, 0.22515451, 0.46387789],
       [0.46179093, 0.37434275, 0.62610208]])

    - random.randint() : 일정 구간의 랜덤 정수의 배열 생성

In [33]:
np.random.randint(0, 10, (3, 3))

array([[8, 8, 4],
       [0, 5, 1],
       [9, 3, 7]])

    - random.normal() : 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
    - 평균 = 0, 표준편차 = 1, 3x3 배열

In [45]:
np.random.normal(0, 1, (3, 3))

array([[-0.74889194, -1.34845715,  1.22256404],
       [ 1.65077433,  0.55010947,  1.08745155],
       [-0.08725409, -0.61637836, -0.75929348]])

    - random.rand() : 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [47]:
np.random.rand(3, 3)

array([[0.66254542, 0.82464405, 0.33274127],
       [0.24904084, 0.13062529, 0.58223747],
       [0.89797243, 0.32257025, 0.4900745 ]])

    - random.randn() : 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [48]:
np.random.randn(3, 3)

array([[ 0.56296921,  0.33476765, -0.14751155],
       [-0.38244891,  0.38518821,  0.17979609],
       [ 0.23601441, -0.00138113, -0.40963162]])

### 표준 데이터 타입

In [49]:
np.zeros(20, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
np.ones((3, 3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [51]:
np.full((3, 3), 1.0, dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성

In [52]:
date = np.array('2020-01-01', dtype = np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [53]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [54]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [56]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

## 배열 조회

### 배열 속성 정보

In [59]:
def array_info(array):
    print(array)
    print('ndim:', array.ndim)
    print('shape:', array.shape)
    print('dtype:', array.dtype)
    print('size:', array.size)
    print('itemsize:', array.itemsize)
    print('nbytes:', array.nbytes)
    print('strides:', array.strides)

In [60]:
array_info(a1)

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtype: int32
size: 5
itemsize: 4
nbytes: 20
strides: (4,)


In [61]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int32
size: 9
itemsize: 4
nbytes: 36
strides: (12, 4)


In [62]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int32
size: 27
itemsize: 4
nbytes: 108
strides: (36, 12, 4)


### 인덱싱(Indexing)

In [65]:
print(a1)
print(a1[0])
print(a1[1])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
5
5
4


In [70]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, 1])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [71]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[2, 2, 2])
print(a3[2, -1, -1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


### 슬라이싱(Slicing)
    - 슬라이싱 구문 : a[start:stop:step]
    - 기본값 : start = 0, stop = ndim, step = 1

In [72]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [73]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :3])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

    * 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
    * True 값인 인덱스의 값만 조회

In [76]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])   # True 값만 출력
bi = [True, False, True, True, False]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [106]:
print(a2)
bi = np.random.randint(0, 2, (3, 3), dtype = bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True  True False]
 [ True False False]
 [ True  True  True]]
[1 2 4 7 8 9]


### 팬시 인덱싱(Fancy Indedxing)

In [109]:
print(a1)
print([a1[0], a1[2]])
ind = [0, 2]
print(a1[ind])
ind = np.array([[0, 1],
               [2, 0]])
print(a1[ind])

[4 5 6 4 5]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


In [111]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

    * `insert()`: 배열의 특정 위치에 값 삽입
    * axis를 지정하지 않으면 1차원 배열로 변환
    * 추가할 방향을 axis로 지정
    * 원본 배열 변경없이 새로운 배열 반환

In [114]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[ 4  5 10  6  4  5]


In [116]:
print(a2)
b2 = np.insert(a2, 1, 10, axis = 0)
print(b2)
c2 = np.insert(a2, 1, 10, axis = 1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

    * 배열의 인덱싱으로 접근하여 값 수정

In [201]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[9 0 3 0 0]
[1 2 3 0 0]
[9 2 3 0 0]
[9 0 3 0 0]
[9 4 3 4 4]


In [204]:
print(a2)
a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
a2[0] = 1
print(a2)
a2[1:, 2] = 0
print(a2)
row = np.array([0, 1])
col = np.array([1, 2])
a2[row, col] = 0
print(a2)

[[1 1 1]
 [4 2 0]
 [7 8 0]]
[[1 1 1]
 [4 2 0]
 [7 8 3]]
[[1 1 1]
 [4 2 0]
 [7 8 0]]
[[1 0 1]
 [4 2 0]
 [7 8 0]]


### 배열 값 삭제<br>

    * `delete()`: 배열의 특정 위치에 값 삭제
    * axis를 지정하지 않으면 1차원 배열로 변환
    * 삭제할 방향을 axis로 지정
    * 원본 배열 변경없이 새로운 배열 반환

In [207]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [209]:
print(a2)
b2 = np.delete(a2, 1, axis = 0)
print(b2)
c2 = np.delete(a2, 1, axis = 1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 0]]
[[1 0 1]
 [7 8 0]]
[[1 1]
 [4 0]
 [7 0]]


### 배열 복사

    * 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [214]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print(a2_sub)
a2_sub[:, 1] = 0
print(a2_sub)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 0]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 0]]


    * copy() : 배열이나 하위배열내의 값을 명시적으로 복사

In [215]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 0]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 0]]


## 배열 변환

### 배열 전치 및 축 변경

In [216]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 0]
 [7 8 0]]
[[1 4 7]
 [0 0 8]
 [1 0 0]]


In [217]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [218]:
print(a2)
print(a2.swapaxes(1, 0))

[[1 0 1]
 [4 0 0]
 [7 8 0]]
[[1 4 7]
 [0 0 8]
 [1 0 0]]


In [219]:
print(a3)
print(a3.swapaxes(0, 1))
print(a3.swapaxes(1, 2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화

    * `reshape()`: 배열의 형상을 변경

In [221]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


    * `newaxis()`: 새로운 축 추가

In [223]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경
    * 배열 모양만 변경

In [224]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize((5, 2))
print(n2)

[[5 3 4 9 8]
 [4 0 5 5 3]]
[[5 3]
 [4 9]
 [8 4]
 [0 5]
 [5 3]]


    * 배열 크기 증가
    * 남은 공간은 0으로 채워짐

In [225]:
n2.resize((5, 5))
print(n2)

[[5 3 4 9 8]
 [4 0 5 5 3]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


    * 배열 크기 감소
    * 포함되지 않은 값은 삭제됨

In [226]:
n2.resize((3, 3))
print(n2)

[[5 3 4]
 [9 8 4]
 [0 5 5]]


### 배열 추가

    * `append()`: 배열의 끝에 값 추가

In [227]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


    * axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [229]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


    * axis를 0으로 지정
    * shape[0]을 제외한 나머지 shape은 같아야 함

In [230]:
c2 = np.append(a2, b2, axis = 0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


    * axis를 1로 지정
    * shape[1]을 제외한 나머지 shape은 같아야 함

In [231]:
c2 = np.append(a2, b2, axis = 1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

    * `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [232]:
a1 = np.array([1, 3, 5])
b2 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 9, 3, 4, 4])

In [233]:
c1 = np.array([7, 8, 9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 9, 3, 4, 4, 7, 8, 9])

In [236]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [237]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([a2, a2], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

    * `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [238]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

    * `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [239]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

    * `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [240]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

    * `stack()`: 새로운 차원으로 연결

In [241]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

    * `split()`: 배열 분할

In [245]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


    * `vsplit()`: 수직 분할, 1차원으로 분할

In [247]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


    * `hsplit()`: 수평 분할, 2차원으로 분할

In [248]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


    * `dsplit()`: 깊이 분할, 3차원으로 분할

In [250]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)s

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


## 배열 연산

    * NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
    * 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
    * 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

![nn](fig_broadcast_visual_1.png)

In [253]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)

a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(a1 + a2)

b2 = np.array([1, 2, 3]).reshape(3, 1)
print(b2)
print(a1 + b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

|연산자|범용 함수|설명|
|------|---------|----|
|+|np.add|덧셈|
|-|np.subtract|뺄셈|
|-|np.negative|단항 음수|
|*|np.multiply|곱셈|
|/|np.divide|나눗셈|
|//|np.floor_divide|나눗셈 내림|
|**|np.power|지수 연산|
|%|np.mod|나머지 연산|

In [261]:
a1 = np.arange(1, 10)
print(a1)
print(a1 + 1)
print(np.add(a1, 10))
print(a1 - 2)
print(np.subtract(a1, 10))
print(-a1)
print(np.negative(a1))
print(a1 * 2)
print(np.multiply(a1, 2))
print(a1 / 2)
print(np.divide(a1, 2))
print(a1 // 2)
print(np.floor_divide(a1, 2))
print(a1 ** 2)
print(np.power(a1, 2))
print(a1 % 2)
print(np.mod(a1, 2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [262]:
a1 = np.arange(1, 10)
print(a1)
b1 = np.random.randint(1, 10, size = 9)
print(b1)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[9 7 4 8 5 8 6 4 3]
[10  9  7 12 10 14 13 12 12]
[-8 -5 -1 -4  0 -2  1  4  6]
[ 9 14 12 32 25 48 42 32 27]
[0.11111111 0.28571429 0.75       0.5        1.         0.75
 1.16666667 2.         3.        ]
[0 0 0 0 1 0 1 2 3]
[      1     128      81   65536    3125 1679616  117649    4096     729]
[1 2 3 4 0 6 1 0 0]


In [264]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.random.randint(1, 10, size = (3, 3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 7 5]
 [7 1 3]
 [1 6 2]]
[[ 8  9  8]
 [11  6  9]
 [ 8 14 11]]
[[-6 -5 -2]
 [-3  4  3]
 [ 6  2  7]]
[[ 7 14 15]
 [28  5 18]
 [ 7 48 18]]
[[0.14285714 0.28571429 0.6       ]
 [0.57142857 5.         2.        ]
 [7.         1.33333333 4.5       ]]
[[0 0 0]
 [0 5 2]
 [7 1 4]]
[[     1    128    243]
 [ 16384      5    216]
 [     7 262144     81]]
[[1 2 3]
 [4 0 0]
 [0 2 1]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [267]:
a1 = np.random.randint(-10, 10, size = 5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[ 7 -7 -5  4 -5]
[7 7 5 4 5]
[7 7 5 4 5]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [268]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[ 7 -7 -5  4 -5]
[49 49 25 16 25]
[2.64575131        nan        nan 2.                nan]


<ipython-input-268-4e034cb7ea92>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


#### 지수와 로그 함수 (Exponential and Log Function)

In [269]:
a1 = np.random.randint(1, 10, size = 5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1, 2))

[5 4 3 6 1]
[148.4131591   54.59815003  20.08553692 403.42879349   2.71828183]
[32. 16.  8. 64.  2.]
[25 16  9 36  1]


In [270]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[5 4 3 6 1]
[1.60943791 1.38629436 1.09861229 1.79175947 0.        ]
[2.32192809 2.         1.5849625  2.5849625  0.        ]
[0.69897    0.60205999 0.47712125 0.77815125 0.        ]


#### 삼각 함수(Trigonometrical Function)


In [271]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [272]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [275]:
a2 = np.random.randint(1, 10, size = (3, 3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis = 0), np.sum(a2, axis = 0))
print(a2.sum(axis = 1), np.sum(a2, axis = 1))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
58 58
[21 16 21] [21 16 21]
[21 18 19] [21 18 19]


#### cumsum(): 누적합 계산

In [276]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis = 0))
print(np.cumsum(a2, axis = 1))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
[ 7 13 21 28 33 39 46 51 58]
[[ 7  6  8]
 [14 11 14]
 [21 16 21]]
[[ 7 13 21]
 [ 7 12 18]
 [ 7 12 19]]


#### diff(): 차분 계산

In [277]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis = 0))
print(np.diff(a2, axis = 1))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
[[-1  2]
 [-2  1]
 [-2  2]]
[[ 0 -1 -2]
 [ 0  0  1]]
[[-1  2]
 [-2  1]
 [-2  2]]


#### prod(): 곱 계산

In [278]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis = 0))
print(np.prod(a2, axis = 1))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
17287200
[343 150 336]
[336 210 245]


#### cumprod(): 누적곱 계산

In [279]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis = 0))
print(np.cumprod(a2, axis = 1))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
[       7       42      336     2352    11760    70560   493920  2469600
 17287200]
[[  7   6   8]
 [ 49  30  48]
 [343 150 336]]
[[  7  42 336]
 [  7  35 210]
 [  7  35 245]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [280]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[21 21 21]
 [18 18 18]
 [19 19 19]]
[[21 21 21]
 [18 18 18]
 [19 19 19]]


#### tensordot(): 텐서곱 계산

In [281]:
print(a2)
print(b2)
print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes = 0))
print(np.tensordot(a2, b2, axes = 1))   # matmul / dot 값과 똑같은 결과

[[7 6 8]
 [7 5 6]
 [7 5 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
58
[[[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]]
[[21 21 21]
 [18 18 18]
 [19 19 19]]


#### cross(): 벡터곱

In [282]:
x = [1, 2, 3]
y = [4, 5, 6]
print(np.cross(x, y))

[-3  6 -3]


#### inner()/outer(): 내적/외적

In [283]:
print(a2)
print(b2)
print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[21 21 21]
 [18 18 18]
 [19 19 19]]
[[7 7 7 7 7 7 7 7 7]
 [6 6 6 6 6 6 6 6 6]
 [8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 7 7 7]
 [5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7]
 [5 5 5 5 5 5 5 5 5]
 [7 7 7 7 7 7 7 7 7]]


#### mean(): 평균 계산

In [284]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis = 0))
print(np.mean(a2, axis = 1))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
6.444444444444445
[7.         5.33333333 7.        ]
[7.         6.         6.33333333]


#### std(): 표준 편차 계산

In [285]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis = 0))
print(np.std(a2, axis = 1))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
0.9558139185602919
[0.         0.47140452 0.81649658]
[0.81649658 0.81649658 0.94280904]


#### var(): 분산 계산

In [286]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis = 0))
print(np.var(a2, axis = 1))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
0.9135802469135802
[0.         0.22222222 0.66666667]
[0.66666667 0.66666667 0.88888889]


#### min(): 최소값

In [287]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis = 0))
print(np.min(a2, axis = 1))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
5
[7 5 6]
[6 5 5]


#### max(): 최대값

In [288]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis = 0))
print(np.max(a2, axis = 1))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
8
[7 6 8]
[8 7 7]


#### argmin(): 최소값 인덱스

In [289]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis = 0))
print(np.argmin(a2, axis = 1))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
4
[0 1 1]
[1 1 1]


#### argmax(): 최대값 인덱스

In [290]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis = 0))
print(np.argmax(a2, axis = 1))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
2
[0 0 0]
[2 0 0]


#### median(): 중앙값

In [291]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis = 0))
print(np.median(a2, axis = 1))

[[7 6 8]
 [7 5 6]
 [7 5 7]]
7.0
[7. 5. 7.]
[7. 6. 7.]


#### percentile(): 백분위 수

![nn](numpy-percentile-1.png)

In [292]:
a1 = np.array([0, 1, 2, 3])
print(a1)
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation = 'linear'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation = 'higher'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation = 'lower'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation = 'nearest'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation = 'midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()
#### all()

In [295]:
a2 = np.array([[False, False, False],
             [False, True, True],
             [False, True, True]])
print(a2)
print(np.any(a2))
print(np.any(a2, axis = 0))
print(np.any(a2, axis = 1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


In [297]:
a2 = np.array([[False, False, True],
             [True, True, True],
             [False, True, True]])
print(a2)
print(np.all(a2))
print(np.all(a2, axis = 0))
print(np.all(a2, axis = 1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교 연산(Comparison Operators)


In [301]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [307]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5))
print(np.sum(a2 > 5, axis = 0))
print(np.sum(a2 > 5, axis = 1))
print(np.any(a2 > 5, axis = 0))
print(np.any(a2 > 5, axis = 1))
print(np.all(a2 > 5, axis = 0))
print(np.all(a2 > 5, axis = 0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
[ True  True  True]
[False  True  True]
[False False False]
[False False False]


In [308]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(b1)
print(np.isclose(a1, b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [312]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)

In [317]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

print((a2 > 5) & (a2 < 8))
print(a2[(a2 > 5) & (a2 < 8)])

print((a2 > 5) | (a2 < 8))
print(a2[(a2 > 5) | (a2 < 8)])

print((a2 > 5) ^ (a2 < 8))
print(a2[(a2 > 5) ^ (a2 < 8)])

print(~(a2 > 5))
print(a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [320]:
a1 = np.random.randint(1, 10, size = 10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1))     # 순서대로 index 값을 출력해줌
print(a1)
print(a1.sort())          # a1 자체를 정렬 해줌.
print(a1)

[5 6 5 4 5 9 1 6 1 4]
[1 1 4 4 5 5 5 6 6 9]
[5 6 5 4 5 9 1 6 1 4]
[6 8 3 9 0 2 4 1 7 5]
[5 6 5 4 5 9 1 6 1 4]
None
[1 1 4 4 5 5 5 6 6 9]


In [321]:
a2 = np.random.randint(1, 10, size = (3, 3))
print(a2)
print(np.sort(a2, axis = 0))
print(np.sort(a2, axis = 1))

[[4 3 6]
 [1 6 6]
 [1 9 1]]
[[1 3 1]
 [1 6 6]
 [4 9 6]]
[[3 4 6]
 [1 6 6]
 [1 1 9]]


#### 부분 정렬

    * `partition()`: 배열에서 k개의 작은 값을 반환

In [322]:
a1 = np.random.randint(1, 10, size = 10)
print(a1)
print(np.partition(a1, 3))

[4 9 4 2 3 8 1 4 4 1]
[2 1 1 3 9 8 4 4 4 4]


In [324]:
a2 = np.random.randint(1, 10, size = (5, 5))
print(a2)
print(np.partition(a2, 3))
print(np.partition(a2, 3, axis = 0))
print(np.partition(a2, 3, axis = 1))

[[3 6 7 3 8]
 [5 6 1 9 3]
 [1 1 1 6 9]
 [8 2 4 3 3]
 [8 8 8 7 4]]
[[3 3 6 7 8]
 [1 3 5 6 9]
 [1 1 1 6 9]
 [3 3 2 4 8]
 [7 4 8 8 8]]
[[1 2 4 3 3]
 [3 1 1 3 4]
 [5 6 1 6 3]
 [8 6 7 7 8]
 [8 8 8 9 9]]
[[3 3 6 7 8]
 [1 3 5 6 9]
 [1 1 1 6 9]
 [3 3 2 4 8]
 [7 4 8 8 8]]


## 배열 입출력<br>
    - 파일로 저장 , 불러오기

In [325]:
a2 = np.random.randint(1, 10, size = (5, 5))
print(a2)
np.save('a', a2)

[[1 4 6 6 5]
 [4 8 1 6 8]
 [4 3 5 8 5]
 [4 2 2 4 6]
 [6 6 1 5 5]]


In [326]:
b2 = np.random.randint(1, 10, size = (5, 5))
print(b2)
np.savez('ab', a2, b2)

[[4 2 4 3 4]
 [4 5 2 6 8]
 [2 2 8 3 5]
 [8 1 2 4 7]
 [3 5 5 2 3]]


In [328]:
npy = np.load('a.npy')
print(npy)

[[1 4 6 6 5]
 [4 8 1 6 8]
 [4 3 5 8 5]
 [4 2 2 4 6]
 [6 6 1 5 5]]


In [332]:
npz = np.load('ab.npz')
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[1 4 6 6 5]
 [4 8 1 6 8]
 [4 3 5 8 5]
 [4 2 2 4 6]
 [6 6 1 5 5]]
[[4 2 4 3 4]
 [4 5 2 6 8]
 [2 2 8 3 5]
 [8 1 2 4 7]
 [3 5 5 2 3]]


In [334]:
print(a2)
np.savetxt('a.csv', a2, delimiter = ',')

[[1 4 6 6 5]
 [4 8 1 6 8]
 [4 3 5 8 5]
 [4 2 2 4 6]
 [6 6 1 5 5]]


In [336]:
csv = np.loadtxt('a.csv', delimiter = ',')
print(csv)

[[1. 4. 6. 6. 5.]
 [4. 8. 1. 6. 8.]
 [4. 3. 5. 8. 5.]
 [4. 2. 2. 4. 6.]
 [6. 6. 1. 5. 5.]]


In [337]:
print(b2)
np.savetxt('b.csv', b2, delimiter=',', fmt = '%.2e', header = 'c1, c2, c3, c4, c5')

[[4 2 4 3 4]
 [4 5 2 6 8]
 [2 2 8 3 5]
 [8 1 2 4 7]
 [3 5 5 2 3]]


In [338]:
csv = np.loadtxt('b.csv', delimiter = ',')
print(csv)

[[4. 2. 4. 3. 4.]
 [4. 5. 2. 6. 8.]
 [2. 2. 8. 3. 5.]
 [8. 1. 2. 4. 7.]
 [3. 5. 5. 2. 3.]]
