# Pandas

- 부동 소수점이 아닌 데이터뿐만 아니라 부동 소수점 데이터에서도 결측 데이터를 쉽게 처리
- 크기변이성(Size mutability) : DataFrame 및 고차원객체에서 열을 삽입 및 삭제 가능
- 자동 및 명시적(explicit) 데이터 정렬 : 객체를 라벨 집합에 명시적으로 정렬하거나, 사용자가 라벨을 무시하고 Series, DataFrame 등의 계산에서 자동으로 데이터 조정 가능
- 데이터세트에서 집계 및 변환을 위한 분할(split), 적용(apply), 결합(combine) 작업을 수행할 수 있는 강력하고 유연한 group-by 함수 제공
- 누락된 데이터 또는 다른 python 및 numpy 데이터 구조에서 서로 다른 인덱싱 데이터를 DataFrame 개체로 쉽게 변환
- 대용량 데이터세트의 지능령 라벨 기반 슬라이싱, 고급 인덱싱 및 부분 집합 구하기 가능
0 직관적인 데이터세트 병합 및 결합
- 데이터세트의 유연한 재구성 및 피벗
- 축의 계층적 라벨링(눈금당 여러개의 라벨을 가질 수 있음)
- 플랫파일(csv 및 구분), Excel파일, 데이터베이스 로딩 및 초고속 HDF5형식의 데이터 저장/로드에 사용되는 강력한 IO도구
- 시계열 특정 기능 : 날짜 범위 생성 및 주파수 변환, 무빙 윈도우(moving window)통계, 날짜 이동 및 지연

In [2]:
import numpy as np
import pandas as pd
pd.__version__

'1.2.4'

## Pandas 객체

- Series 객체

In [5]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [7]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
s[1]

0.25

In [11]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [12]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
             index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [13]:
s['c']

0.5

In [14]:
s[['c', 'd', 'e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [15]:
'b' in s

True

In [16]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
             index = [2, 4, 6, 8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [17]:
s[4]

0.25

In [18]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [19]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
s.value_counts()

0.00    1
1.00    1
0.50    1
0.75    1
0.25    1
dtype: int64

In [22]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [23]:
pop_tuple = {'서울특별시' : 9720846,
            '부산광역시' : 3484423,
            '인천광역시' : 2947217,
            '대구광역시' : 2428925,
            '대전광역시' : 1470480,
            '광주광역시' : 1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3484423
인천광역시    2947217
대구광역시    2428925
대전광역시    1470480
광주광역시    1455048
dtype: int64

In [24]:
population['서울특별시']

9720846

In [26]:
population['서울특별시' : '인천광역시']

서울특별시    9720846
부산광역시    3484423
인천광역시    2947217
dtype: int64

- DataFrame 객체

In [27]:
pd.DataFrame([{'A' : 2, 'B':4, 'D':3}, {'A':4, 'B':5, 'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [28]:
pd.DataFrame(np.random.rand(5, 5),
            columns = ['A', 'B', 'C', 'D', 'E'],
            index = [1, 2, 3, 4,5])

A         B         C         D         E
1  0.399202  0.260817  0.438929  0.716304  0.503384
2  0.520001  0.900612  0.822400  0.070364  0.568879
3  0.826117  0.606429  0.414692  0.376639  0.482361
4  0.629886  0.001630  0.892158  0.752221  0.508970
5  0.203543  0.727786  0.385784  0.126662  0.209478

In [29]:
male_tuple = {'서울특별시' : 4732275,
            '부산광역시' : 1668618,
            '인천광역시' : 1476813,
            '대구광역시' : 1169815,
            '대전광역시' : 734441,
            '광주광역시' : 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1169815
대전광역시     734441
광주광역시     720060
dtype: int64

In [30]:
female_tuple = {'서울특별시' : 4988571,
            '부산광역시' : 1735805,
            '인천광역시' : 1470404,
            '대구광역시' : 1229391,
            '대전광역시' : 736559,
            '광주광역시' : 739488}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229391
대전광역시     736559
광주광역시     739488
dtype: int64

In [82]:
korea_df = pd.DataFrame({'인구수': population,
                        '남자인구수' : male,
                        '여자인구수' : female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3484423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2428925  1169815  1229391
대전광역시  1470480   734441   736559
광주광역시  1455048   720060   739488

In [32]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [33]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [34]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229391
대전광역시     736559
광주광역시     739488
Name: 여자인구수, dtype: int64

In [35]:
korea_df['서울특별시':'인천광역시']

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3484423  1668618  1735805
인천광역시  2947217  1476813  1470404

- Index 객체

In [36]:
idx = pd.Index([2, 4, 6, 8, 10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [37]:
idx[1]

4

In [38]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [40]:
idx[-1:]

Int64Index([10], dtype='int64')

In [41]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [42]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


- Index 연산

In [56]:
idx1 = pd.Index([1, 2, 4, 6, 8])
idx2 = pd.Index([2, 4, 5, 6, 7])
print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2)
print(idx1.intersection(idx2))   # 교집합
print(idx1 & idx2)
print(idx1.union(idx2))          # 두 인덱스를 합
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(1))
print(idx1 ^ idx2)              # 여집합


Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')


<ipython-input-56-a29636cc8867>:7: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  print(idx1 & idx2)
<ipython-input-56-a29636cc8867>:9: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  print(idx1 | idx2)
<ipython-input-56-a29636cc8867>:12: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  print(idx1 ^ idx2)


- 인덱싱(Indexing)

In [57]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
             index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [58]:
s['b']

0.25

In [60]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [61]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [62]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [63]:
s['a' : 'd']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [64]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [65]:
# 특정 조건 주어진 후, 해당 값 출력

s[(s > 0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [66]:
s[['a', 'c', 'e']]

a    0.0
c    0.5
e    1.0
dtype: float64

- Series 인덱싱

In [67]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'],
             index = [1, 3, 5, 7, 9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [68]:
s[1]

'a'

In [70]:
s.iloc[1]

'b'

In [71]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [72]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [73]:
# 비어있는 Index들을 전에 있던 값으로 채우기

s.reindex(range(10), method = 'bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

- DataFrame 인덱싱

In [81]:
korea_df

인구수    남자인구수    여자인구수          남여비율
서울특별시  9720846  4732275  4988571   9486.233633
부산광역시  3484423  1668618  1735805   9612.934633
인천광역시  2947217  1476813  1470404  10043.586661
대구광역시  2428925  1169815  1229391   9515.402341
대전광역시  1470480   734441   736559   9971.244666
광주광역시  1455048   720060   739488   9737.277684

In [75]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1169815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [76]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1169815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [78]:
korea_df.인구수

서울특별시    9720846
부산광역시    3484423
인천광역시    2947217
대구광역시    2428925
대전광역시    1470480
광주광역시    1455048
Name: 인구수, dtype: int64

In [84]:
korea_df['남여비율'] = (korea_df['남자인구수'] * 100 / korea_df['여자인구수'] )
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3484423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2428925  1169815  1229391   95.154023
대전광역시  1470480   734441   736559   99.712447
광주광역시  1455048   720060   739488   97.372777

In [85]:
korea_df.values

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.48442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42892500e+06, 1.16981500e+06, 1.22939100e+06, 9.51540234e+01],
       [1.47048000e+06, 7.34441000e+05, 7.36559000e+05, 9.97124467e+01],
       [1.45504800e+06, 7.20060000e+05, 7.39488000e+05, 9.73727768e+01]])

In [86]:
korea_df.T

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.720846e+06  3.484423e+06  2.947217e+06  2.428925e+06  1.470480e+06   
남자인구수  4.732275e+06  1.668618e+06  1.476813e+06  1.169815e+06  7.344410e+05   
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  1.229391e+06  7.365590e+05   
남여비율   9.486234e+01  9.612935e+01  1.004359e+02  9.515402e+01  9.971245e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  7.200600e+05  
여자인구수  7.394880e+05  
남여비율   9.737278e+01

In [87]:
korea_df.values[0]

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [88]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3484423
인천광역시    2947217
대구광역시    2428925
대전광역시    1470480
광주광역시    1455048
Name: 인구수, dtype: int64

In [89]:
korea_df.loc[:'인천광역시', :'남자인구수']

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3484423  1668618
인천광역시  2947217  1476813

In [91]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3484423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2428925  1169815  1229391   95.154023

In [92]:
korea_df.loc[(korea_df.인구수 < 2000000)]

인구수   남자인구수   여자인구수       남여비율
대전광역시  1470480  734441  736559  99.712447
광주광역시  1455048  720060  739488  97.372777

In [93]:
korea_df.loc[(korea_df.인구수 > 2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3484423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [94]:
korea_df.loc[korea_df.남여비율 > 100]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [95]:
korea_df.loc[(korea_df.인구수 > 2500000) & (korea_df.남여비율 > 100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [96]:
korea_df.iloc[:3, :2]

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3484423  1668618
인천광역시  2947217  1476813

- 다중인덱싱(Multi Indexing)
    - 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터처리
    - 단일인덱스 내에 여러 인덱스를 포함하는 다중인덱싱

In [97]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3484423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2428925  1169815  1229391   95.154023
대전광역시  1470480   734441   736559   99.712447
광주광역시  1455048   720060   739488   97.372777

In [98]:
idx_tuples = [('서울특별시', 2010), ('서울특별시', 2020),
            ('부산광역시', 2010), ('부산광역시', 2020),
            ('인천광역시', 2010), ('인천광역시', 2020),
            ('대구광역시', 2010), ('대구광역시', 2020),
            ('대전광역시', 2010), ('대전광역시', 2020),
            ('광주광역시', 2010), ('광주광역시', 2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [99]:
pop_tuples = [1031245, 9728846, 2567910, 3404423, 2758296, 2947217, 2511676, 2427954, 1503664, 1471040, 1454636, 1455048]
population = pd.Series(pop_tuples, index = idx_tuples)
population

(서울특별시, 2010)    1031245
(서울특별시, 2020)    9728846
(부산광역시, 2010)    2567910
(부산광역시, 2020)    3404423
(인천광역시, 2010)    2758296
(인천광역시, 2020)    2947217
(대구광역시, 2010)    2511676
(대구광역시, 2020)    2427954
(대전광역시, 2010)    1503664
(대전광역시, 2020)    1471040
(광주광역시, 2010)    1454636
(광주광역시, 2020)    1455048
dtype: int64

In [100]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [101]:
population = population.reindex(midx)
population

서울특별시  2010    1031245
       2020    9728846
부산광역시  2010    2567910
       2020    3404423
인천광역시  2010    2758296
       2020    2947217
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
광주광역시  2010    1454636
       2020    1455048
dtype: int64

In [102]:
population[:, 2010]

서울특별시    1031245
부산광역시    2567910
인천광역시    2758296
대구광역시    2511676
대전광역시    1503664
광주광역시    1454636
dtype: int64

In [105]:
population['대전광역시', :]

2010    1503664
2020    1471040
dtype: int64

In [106]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시  1454636  1455048
대구광역시  2511676  2427954
대전광역시  1503664  1471040
부산광역시  2567910  3404423
서울특별시  1031245  9728846
인천광역시  2758296  2947217

In [107]:
korea_mdf.stack()

광주광역시  2010    1454636
       2020    1455048
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
부산광역시  2010    2567910
       2020    3404423
서울특별시  2010    1031245
       2020    9728846
인천광역시  2010    2758296
       2020    2947217
dtype: int64

In [108]:
male_tuple = [5111259, 4732275,
             1773170, 1668618, 
             1390356, 1476813, 
             1255245, 1198815, 
             753648, 734441, 
             721780, 720060]
male_tuple

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [109]:
korea_mdf = pd.DataFrame({'총인구수': population, 
                         '남자인구수' : male_tuple})
korea_mdf

총인구수    남자인구수
서울특별시 2010  1031245  5111259
      2020  9728846  4732275
부산광역시 2010  2567910  1773170
      2020  3404423  1668618
인천광역시 2010  2758296  1390356
      2020  2947217  1476813
대구광역시 2010  2511676  1255245
      2020  2427954  1198815
대전광역시 2010  1503664   753648
      2020  1471040   734441
광주광역시 2010  1454636   721780
      2020  1455048   720060

In [110]:
female_tuples = [5201286, 4988571,
                1794740, 1735805,
                1367940, 1470404,
                1256431, 1229139,
                750016, 736599,
                732856, 734988]
female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [112]:
korea_mdf = pd.DataFrame({'총인구수': population, 
                         '남자인구수' : male_tuple,
                         '여자인구수': female_tuples})
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  1031245  5111259  5201286
      2020  9728846  4732275  4988571
부산광역시 2010  2567910  1773170  1794740
      2020  3404423  1668618  1735805
인천광역시 2010  2758296  1390356  1367940
      2020  2947217  1476813  1470404
대구광역시 2010  2511676  1255245  1256431
      2020  2427954  1198815  1229139
대전광역시 2010  1503664   753648   750016
      2020  1471040   734441   736599
광주광역시 2010  1454636   721780   732856
      2020  1455048   720060   734988

In [113]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [114]:
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [115]:
korea_mdf = pd.DataFrame({'총인구수': population, 
                         '남자인구수' : male_tuple,
                         '여자인구수': female_tuples,
                         '남여비율' : ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  1031245  5111259  5201286   98.269140
      2020  9728846  4732275  4988571   94.862336
부산광역시 2010  2567910  1773170  1794740   98.798155
      2020  3404423  1668618  1735805   96.129346
인천광역시 2010  2758296  1390356  1367940  101.638668
      2020  2947217  1476813  1470404  100.435867
대구광역시 2010  2511676  1255245  1256431   99.905606
      2020  2427954  1198815  1229139   97.532907
대전광역시 2010  1503664   753648   750016  100.484256
      2020  1471040   734441   736599   99.707032
광주광역시 2010  1454636   721780   732856   98.488653
      2020  1455048   720060   734988   97.968946

- 다중인덱싱 생성

In [116]:
df = pd.DataFrame(np.random.rand(6, 3),
                  index = [['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]],
                  columns = ['c1', 'c2', 'c3'])
df

c1        c2        c3
a 1  0.969247  0.109416  0.191030
  2  0.211611  0.153657  0.587700
b 1  0.191823  0.185228  0.676615
  2  0.385451  0.395749  0.072623
c 1  0.898000  0.177794  0.313497
  2  0.245923  0.659384  0.391564

In [117]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [119]:
pd.MultiIndex.from_tuples([('a',1), ('a', 2), ('b', 1), ('b', 2), ('c', 1), ('c', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [120]:
pd.MultiIndex.from_product((['a', 'b', 'c'], [1, 2]))

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [121]:
pd.MultiIndex(levels = [['a','b','c'], [1, 2]],
             codes = [[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [122]:
population

서울특별시  2010    1031245
       2020    9728846
부산광역시  2010    2567910
       2020    3404423
인천광역시  2010    2758296
       2020    2947217
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
광주광역시  2010    1454636
       2020    1455048
dtype: int64

In [124]:
population.index.names = ['행정구역', '년도']
population

행정구역   년도  
서울특별시  2010    1031245
       2020    9728846
부산광역시  2010    2567910
       2020    3404423
인천광역시  2010    2758296
       2020    2947217
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
광주광역시  2010    1454636
       2020    1455048
dtype: int64

In [126]:
idx = pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]],
                                 names = ['name1', 'name2'])
cols = pd.MultiIndex.from_product([['c1', 'c2', 'c3'], [1, 2]],
                                  names = ['col_name1', 'col_name2'])
data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index = idx, columns = cols)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -0.68 -0.44 -0.66  0.06 -1.79 -0.79
      2      0.58  0.44  0.04 -0.53  1.00 -1.59
b     1      1.26  0.34 -0.57  1.11 -0.16  1.01
      2      1.41 -0.35  0.60 -0.55  0.71 -1.50
c     1      0.31  0.21 -1.31  1.61 -1.98  0.10
      2     -0.77  0.03 -0.65 -1.13 -1.06 -0.76

In [127]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1     -0.66  0.06
      2      0.04 -0.53
b     1     -0.57  1.11
      2      0.60 -0.55
c     1     -1.31  1.61
      2     -0.65 -1.13

- 인덱싱 및 슬라이싱

In [128]:
population

행정구역   년도  
서울특별시  2010    1031245
       2020    9728846
부산광역시  2010    2567910
       2020    3404423
인천광역시  2010    2758296
       2020    2947217
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
광주광역시  2010    1454636
       2020    1455048
dtype: int64

In [129]:
population['인천광역시', 2010]

2758296

In [132]:
population[:, 2010]

행정구역
서울특별시    1031245
부산광역시    2567910
인천광역시    2758296
대구광역시    2511676
대전광역시    1503664
광주광역시    1454636
dtype: int64

In [133]:
population[population > 3000000]

행정구역   년도  
서울특별시  2020    9728846
부산광역시  2020    3404423
dtype: int64

In [134]:
population[['대구광역시', '대전광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [135]:
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -0.68 -0.44 -0.66  0.06 -1.79 -0.79
      2      0.58  0.44  0.04 -0.53  1.00 -1.59
b     1      1.26  0.34 -0.57  1.11 -0.16  1.01
      2      1.41 -0.35  0.60 -0.55  0.71 -1.50
c     1      0.31  0.21 -1.31  1.61 -1.98  0.10
      2     -0.77  0.03 -0.65 -1.13 -1.06 -0.76

In [138]:
mdf['c2', 1]

name1  name2
a      1       -0.66
       2        0.04
b      1       -0.57
       2        0.60
c      1       -1.31
       2       -0.65
Name: (c2, 1), dtype: float64

In [139]:
mdf.iloc[:3, :4]

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1     -0.68 -0.44 -0.66  0.06
      2      0.58  0.44  0.04 -0.53
b     1      1.26  0.34 -0.57  1.11

In [140]:
mdf.loc[:, ('c2', 1)]

name1  name2
a      1       -0.66
       2        0.04
b      1       -0.57
       2        0.60
c      1       -1.31
       2       -0.65
Name: (c2, 1), dtype: float64

In [142]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:, 2], idx_slice[:, 2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2      0.44 -0.53 -1.59
b     2     -0.35 -0.55 -1.50
c     2      0.03 -1.13 -0.76

- 다중 인덱스 재정렬

In [143]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

- 데이터 연산

In [3]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    1
1    0
2    1
3    3
4    2
dtype: int32

In [4]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                 columns = ['A', 'B', 'C'])
df

A  B  C
0  7  7  9
1  4  0  7
2  6  3  1

In [5]:
np.exp(s)

0     2.718282
1     1.000000
2     2.718282
3    20.085537
4     7.389056
dtype: float64

In [6]:
np.cos(df * np.pi / 4)

A         B         C
0  7.071068e-01  0.707107  0.707107
1 -1.000000e+00  1.000000  0.707107
2 -1.836970e-16 -0.707107  0.707107

In [7]:
s1 = pd.Series([1, 3, 5, 7, 9], index = [0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index = [1, 2, 3,4, 5])
s1 + s2
# index가 매칭이 안되는 값들은 NaN 출력

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [9]:
s1.add(s2, fill_value = 0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [10]:
df1 = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                  columns = list('ACD'))
df1

A  C  D
0  7  9  7
1  3  2  3
2  5  3  5

In [11]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5, 5)),
                  columns = list('BAECD'))
df2

B   A   E   C   D
0  10   9  19  11   3
1  15   1   1   6   6
2   1   2   2  15  13
3   9  18   2   1   2
4   9   2   2   2  12

In [13]:
df1 +df2

A   B     C     D   E
0  16.0 NaN  20.0  10.0 NaN
1   4.0 NaN   8.0   9.0 NaN
2   7.0 NaN  18.0  18.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [15]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value = fvalue)

A          B          C          D          E
0  16.000000  14.888889  20.000000  10.000000  23.888889
1   4.000000  19.888889   8.000000   9.000000   5.888889
2   7.000000   5.888889  18.000000  18.000000   6.888889
3  22.888889  13.888889   5.888889   6.888889   6.888889
4   6.888889  13.888889   6.888889  16.888889   6.888889

- 연산자 범용 함수

    - add()

In [16]:
a = np.random.randint(1, 10, size =(3, 3))
a

array([[6, 6, 2],
       [5, 4, 7],
       [3, 3, 6]])

In [17]:
a + a[0]

array([[12, 12,  4],
       [11, 10,  9],
       [ 9,  9,  8]])

In [18]:
df = pd.DataFrame(a, columns = list('ABC'))
df

A  B  C
0  6  6  2
1  5  4  7
2  3  3  6

In [19]:
df + df.iloc[0]

# a + a[0]  =  df + df.iloc[0]  =  df.add(df.iloc[0])


A   B  C
0  12  12  4
1  11  10  9
2   9   9  8

In [20]:
df.add(df.iloc[0])

A   B  C
0  12  12  4
1  11  10  9
2   9   9  8

    - 뺄셈 : sub() / subtract()

In [21]:
a

array([[6, 6, 2],
       [5, 4, 7],
       [3, 3, 6]])

In [22]:
a - a[0]

array([[ 0,  0,  0],
       [-1, -2,  5],
       [-3, -3,  4]])

In [23]:
df

A  B  C
0  6  6  2
1  5  4  7
2  3  3  6

In [24]:
df - df.iloc[0]

A  B  C
0  0  0  0
1 -1 -2  5
2 -3 -3  4

In [25]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1 -1 -2  5
2 -3 -3  4

In [26]:
df.subtract(df['B'], axis = 0)

A  B  C
0  0  0 -4
1  1  0  3
2  0  0  3

    - 곱셈 : mul() / multiply()

In [30]:
a * a[1]

array([[30, 24, 14],
       [25, 16, 49],
       [15, 12, 42]])

In [29]:
df * df.iloc[1]

A   B   C
0  30  24  14
1  25  16  49
2  15  12  42

In [31]:
df.mul(df.iloc[1])

A   B   C
0  30  24  14
1  25  16  49
2  15  12  42

In [32]:
df.multiply(df.iloc[1])

A   B   C
0  30  24  14
1  25  16  49
2  15  12  42

    - 나눗셈 : truediv() / div() / divide() / floordiv()

In [33]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [0.83333333, 0.66666667, 3.5       ],
       [0.5       , 0.5       , 3.        ]])

In [34]:
df / df.iloc[0]

A         B    C
0  1.000000  1.000000  1.0
1  0.833333  0.666667  3.5
2  0.500000  0.500000  3.0

In [35]:
df.truediv(df.iloc[0])

A         B    C
0  1.000000  1.000000  1.0
1  0.833333  0.666667  3.5
2  0.500000  0.500000  3.0

In [36]:
df.div(df.iloc[1])

A     B         C
0  1.2  1.50  0.285714
1  1.0  1.00  1.000000
2  0.6  0.75  0.857143

In [37]:
df.divide(df.iloc[2])

A         B         C
0  2.000000  2.000000  0.333333
1  1.666667  1.333333  1.166667
2  1.000000  1.000000  1.000000

In [38]:
a // a[0]

array([[1, 1, 1],
       [0, 0, 3],
       [0, 0, 3]], dtype=int32)

In [39]:
df.floordiv(df.iloc[0])

A  B  C
0  1  1  1
1  0  0  3
2  0  0  3

    - 나머지 : mod()

In [40]:
a % a[0]

array([[0, 0, 0],
       [5, 4, 1],
       [3, 3, 0]], dtype=int32)

In [41]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  5  4  1
2  3  3  0

    - pow()

In [42]:
a ** a[0]

array([[46656, 46656,     4],
       [15625,  4096,    49],
       [  729,   729,    36]], dtype=int32)

In [43]:
df.pow(df.iloc[0])

A      B   C
0  46656  46656   4
1  15625   4096  49
2    729    729  36

In [45]:
row = df.iloc[0, ::2]
row

A    6
C    2
Name: 0, dtype: int32

In [46]:
df - row

A   B    C
0  0.0 NaN  0.0
1 -1.0 NaN  5.0
2 -3.0 NaN  4.0

- 정렬(sort)

In [47]:
s = pd.Series(range(5), index = ['A', 'D', 'B', 'C', 'E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [49]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [50]:
s.sort_index()

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [51]:
df = pd.DataFrame(np.random.randint(0, 10, (4, 4)),
                 index = [2, 4, 1, 3],
                 columns = list('BDAC'))
df

B  D  A  C
2  4  0  4  9
4  9  7  2  7
1  6  0  4  6
3  4  5  7  9

In [52]:
df.sort_index()

B  D  A  C
1  6  0  4  6
2  4  0  4  9
3  4  5  7  9
4  9  7  2  7

In [55]:
df.sort_values(by = 'A')

B  D  A  C
4  9  7  2  7
2  4  0  4  9
1  6  0  4  6
3  4  5  7  9

In [58]:
df.sort_values(by = ['A', 'C'])

B  D  A  C
4  9  7  2  7
1  6  0  4  6
2  4  0  4  9
3  4  5  7  9

In [59]:
df.sort_index(axis = 1)

A  B  C  D
2  4  4  9  0
4  2  9  7  7
1  4  6  6  0
3  7  4  9  5

- 순위(Ranking)
    * average : 기본값, 순위에 같은 값을 가지는 항목들의 평균값을 사용
    * min : 같은 값을 가지는 그룹을 낮은 순위로 지정
    * max : 같은 값을 가지는 그룹을 높은 순위로 지정
    * first : 데이터 내의 위치에 따라 순위 지정
    * dense : 같은 그룹 내에서 모두 같은 순위를 적용하지 않고 1씩 증가

In [3]:
s = pd.Series([-2, 4, 7, 3, 0, 7, 5, -4, 2, 6])
s

0   -2
1    4
2    7
3    3
4    0
5    7
6    5
7   -4
8    2
9    6
dtype: int64

In [4]:
s.rank()

0    2.0
1    6.0
2    9.5
3    5.0
4    3.0
5    9.5
6    7.0
7    1.0
8    4.0
9    8.0
dtype: float64

In [5]:
s.rank(method = 'first')
# 동일한 값이 나왔을때 먼저 적혀있는 숫자가 우선적용

0     2.0
1     6.0
2     9.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [6]:
s.rank(method = 'max')

0     2.0
1     6.0
2    10.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

- 고성능 연산

In [7]:
nrows, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [8]:
%timeit df1 + df2 + df3 + df4

83.6 ms ± 1.65 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
%timeit pd.eval('df1 + df2 + df3 + df4')

85 ms ± 3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit df1 * -df2 / (-df3 * df4)

130 ms ± 3.57 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
%timeit pd.eval('df1 * -df2 / (-df3 * df4)')

135 ms ± 3.83 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
%timeit (df1 < df2) & (df2 <= df3) & (df3 != df4)

49.4 ms ± 2.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & (df3 != df4)')

51.3 ms ± 3.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [14]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns = ['A', 'B', 'C', 'D', 'E'])
df.head()

A         B         C         D         E
0  0.124532  0.392943  0.357708  0.523449  0.337990
1  0.665619  0.369886  0.158029  0.412543  0.840122
2  0.050383  0.090577  0.393168  0.832477  0.087572
3  0.071873  0.714956  0.203940  0.085609  0.997333
4  0.353753  0.379785  0.782219  0.546262  0.071966

In [15]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

16.4 ms ± 433 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [16]:
%timeit pd.eval('df.A + df.B / df.C - df.D * df.E')

16.8 ms ± 153 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
# DF의 연산값을 새로운 칼럼을 저장

df.eval('R = A + B / C - D * E', inplace = True)
df.head()

A         B         C         D         E         R
0  0.124532  0.392943  0.357708  0.523449  0.337990  1.046114
1  0.665619  0.369886  0.158029  0.412543  0.840122  2.659648
2  0.050383  0.090577  0.393168  0.832477  0.087572  0.207859
3  0.071873  0.714956  0.203940  0.085609  0.997333  3.492206
4  0.353753  0.379785  0.782219  0.546262  0.071966  0.799962

In [19]:
col_mean = df.mean(1)
df['A'] + col_mean

0         0.588322
1         1.516594
2         0.327389
3         0.999526
4         0.842744
            ...   
999995    1.853232
999996    0.639760
999997    1.362750
999998    0.815046
999999    1.214564
Length: 1000000, dtype: float64

In [20]:
# 외부에 있는 변수(@~~~)를 가져와서 eval 함수를 통해 연산 가능

df.eval('A + @col_mean')

0         0.588322
1         1.516594
2         0.327389
3         0.999526
4         0.842744
            ...   
999995    1.853232
999996    0.639760
999997    1.362750
999998    0.815046
999999    1.214564
Length: 1000000, dtype: float64

In [21]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]

A         B         C         D         E         R
4       0.353753  0.379785  0.782219  0.546262  0.071966  0.799962
12      0.455409  0.449333  0.639106  0.279160  0.637913  0.980393
51      0.102617  0.471834  0.734221  0.576970  0.790822  0.288968
52      0.321566  0.460796  0.933187  0.127390  0.282576  0.779357
56      0.329680  0.172640  0.550320  0.302160  0.424518  0.515117
...          ...       ...       ...       ...       ...       ...
999966  0.065743  0.256143  0.971842  0.441513  0.535596  0.092836
999968  0.365511  0.376708  0.588777  0.659391  0.813441  0.468949
999969  0.245133  0.308892  0.758894  0.559339  0.045781  0.626555
999975  0.238986  0.147422  0.999887  0.139042  0.713796  0.287178
999981  0.257831  0.117840  0.965207  0.243451  0.424974  0.276459

[124829 rows x 6 columns]

In [23]:
pd.eval('df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]')

A         B         C         D         E         R
4       0.353753  0.379785  0.782219  0.546262  0.071966  0.799962
12      0.455409  0.449333  0.639106  0.279160  0.637913  0.980393
51      0.102617  0.471834  0.734221  0.576970  0.790822  0.288968
52      0.321566  0.460796  0.933187  0.127390  0.282576  0.779357
56      0.329680  0.172640  0.550320  0.302160  0.424518  0.515117
...          ...       ...       ...       ...       ...       ...
999966  0.065743  0.256143  0.971842  0.441513  0.535596  0.092836
999968  0.365511  0.376708  0.588777  0.659391  0.813441  0.468949
999969  0.245133  0.308892  0.758894  0.559339  0.045781  0.626555
999975  0.238986  0.147422  0.999887  0.139042  0.713796  0.287178
999981  0.257831  0.117840  0.965207  0.243451  0.424974  0.276459

[124829 rows x 6 columns]

In [25]:
df.query('(A < 0.5) and (B < 0.5) and (C > 0.5)')

A         B         C         D         E         R
4       0.353753  0.379785  0.782219  0.546262  0.071966  0.799962
12      0.455409  0.449333  0.639106  0.279160  0.637913  0.980393
51      0.102617  0.471834  0.734221  0.576970  0.790822  0.288968
52      0.321566  0.460796  0.933187  0.127390  0.282576  0.779357
56      0.329680  0.172640  0.550320  0.302160  0.424518  0.515117
...          ...       ...       ...       ...       ...       ...
999966  0.065743  0.256143  0.971842  0.441513  0.535596  0.092836
999968  0.365511  0.376708  0.588777  0.659391  0.813441  0.468949
999969  0.245133  0.308892  0.758894  0.559339  0.045781  0.626555
999975  0.238986  0.147422  0.999887  0.139042  0.713796  0.287178
999981  0.257831  0.117840  0.965207  0.243451  0.424974  0.276459

[124829 rows x 6 columns]

In [26]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)]

A         B         C         D         E         R
0       0.124532  0.392943  0.357708  0.523449  0.337990  1.046114
2       0.050383  0.090577  0.393168  0.832477  0.087572  0.207859
4       0.353753  0.379785  0.782219  0.546262  0.071966  0.799962
7       0.312933  0.363023  0.248134  0.440530  0.618837  1.503329
12      0.455409  0.449333  0.639106  0.279160  0.637913  0.980393
...          ...       ...       ...       ...       ...       ...
999969  0.245133  0.308892  0.758894  0.559339  0.045781  0.626555
999975  0.238986  0.147422  0.999887  0.139042  0.713796  0.287178
999981  0.257831  0.117840  0.965207  0.243451  0.424974  0.276459
999996  0.279655  0.157733  0.312250  0.337482  0.435769  0.637739
999998  0.263191  0.385419  0.194594  0.182079  0.051383  2.234467

[249528 rows x 6 columns]

In [27]:
df.query('A < @col_mean and B < @col_mean')

A         B         C         D         E         R
0       0.124532  0.392943  0.357708  0.523449  0.337990  1.046114
2       0.050383  0.090577  0.393168  0.832477  0.087572  0.207859
4       0.353753  0.379785  0.782219  0.546262  0.071966  0.799962
7       0.312933  0.363023  0.248134  0.440530  0.618837  1.503329
12      0.455409  0.449333  0.639106  0.279160  0.637913  0.980393
...          ...       ...       ...       ...       ...       ...
999969  0.245133  0.308892  0.758894  0.559339  0.045781  0.626555
999975  0.238986  0.147422  0.999887  0.139042  0.713796  0.287178
999981  0.257831  0.117840  0.965207  0.243451  0.424974  0.276459
999996  0.279655  0.157733  0.312250  0.337482  0.435769  0.637739
999998  0.263191  0.385419  0.194594  0.182079  0.051383  2.234467

[249528 rows x 6 columns]

- 데이터 결합

    - Concat() / Append()

In [28]:
s1 = pd.Series(['a', 'b'], index = [1, 2])
s2 = pd.Series(['c', 'd'], index = [3, 4])
pd.concat([s1, s2])

1    a
2    b
3    c
4    d
dtype: object

In [29]:
def create_df(cols, idx):
    data = {c: [str(c.lower()) + str(i) for i in idx] for c in cols}
    return pd.DataFrame(data, idx)

In [30]:
df1 = create_df('AB', [1, 2])
df1

A   B
1  a1  b1
2  a2  b2

In [31]:
df2 = create_df('AB', [3, 4])
df2

A   B
3  a3  b3
4  a4  b4

In [33]:
pd.concat([df1, df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [34]:
df3 = create_df('AB', [0, 1])
df3

A   B
0  a0  b0
1  a1  b1

In [35]:
df4 = create_df('CD', [0, 1])
df4

C   D
0  c0  d0
1  c1  d1

In [36]:
pd.concat([df3, df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [44]:
pd.concat([df3, df4], axis = 1)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [45]:
pd.concat([df1, df3])

A   B
1  a1  b1
2  a2  b2
0  a0  b0
1  a1  b1

In [38]:
#pd.concat([df1, df3], verify_integrity = True)

ValueError: Indexes have overlapping values: Int64Index([1], dtype='int64')

In [39]:
pd.concat([df1, df3], ignore_index = True)

A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [40]:
# 멀티인덱스처럼 key가 추가됨.
pd.concat([df1, df3], keys = ['X', 'Y'])

A   B
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [41]:
df5 = create_df('ABC', [1, 2])
df6 = create_df('BCD', [3, 4])
pd.concat([df5, df6])

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [42]:
# 둘다 존재하는 데이터에 대해서만 'inner join' 출력

pd.concat([df5, df6], join = 'inner')

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [43]:
df5.append(df6)

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

    - 병합과 조인
   

In [47]:
df1 = pd.DataFrame({'학생' : ['홍길동', '이순신', '임꺽정', '김유신'],
                   '학과' : ['경영학과', '교육학과', '컴퓨터학과', '통계학과']})
df1

학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [49]:
df2 = pd.DataFrame({'학생' : ['홍길동', '이순신', '임꺽정', '김유신'],
                   '입학년도' : [2012, 2016, 2019, 2020]})
df2

학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [51]:
df3 = pd.merge(df1, df2)
df3

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [52]:
df4 = pd.DataFrame({'학과' : ['경영학과', '교육학과', '컴퓨터학과', '통계학과'],
                   '학과장' : ['황희', '장영실', '안창호', '정약용']})
df4

학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [53]:
pd.merge(df3, df4)

학생     학과  입학년도  학과장
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유신   통계학과  2020  정약용

In [56]:
df5 = pd.DataFrame({'학과' : ['경영학과', '교육학과', '교육학과', '컴퓨터학과', '컴퓨터학과', '통계학과'],
                   '과목' : ['경영개론', '기초수학', '물리학', '프로그래밍', '운영체제', '확률론']})
df5

학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [57]:
pd.merge(df1, df5)

학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [58]:
pd.merge(df1, df2, on = '학생')

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [59]:
df6 = pd.DataFrame({'이름' : ['홍길동', '이순신', '임꺽정' ,'김유신'],
                   '성적' : ['A', 'A+', 'B', 'A+']})
df6

이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  A+

In [60]:
pd.merge(df1, df6, left_on = '학생', right_on = '이름')

학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신  A+

In [63]:
pd.merge(df1, df6, left_on = '학생', right_on = '이름').drop('이름', axis = 1)

학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과  A+

In [64]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')
mdf1

학과
학생        
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [65]:
mdf2

입학년도
학생       
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [67]:
pd.merge(mdf1, mdf2, left_index = True, right_index = True)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [68]:
mdf1.join(mdf2)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [69]:
pd.merge(mdf1, df6, left_index = True, right_on = '이름')

학과   이름  성적
0   경영학과  홍길동   A
1   교육학과  이순신  A+
2  컴퓨터학과  임꺽정   B
3   통계학과  김유신  A+

In [70]:
df7 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정'],
                   '주문음식' : ['햄버거', '피자', '짜장면']})
df7

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면

In [71]:
df8 = pd.DataFrame({'이름': ['홍길동', '이순신', '김유신'],
                   '주문음료' : ['콜라', '사이다', '커피']})
df8

이름 주문음료
0  홍길동   콜라
1  이순신  사이다
2  김유신   커피

In [72]:
pd.merge(df7, df8)

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [73]:
# 공통된 부분만
pd.merge(df7, df8, how = 'inner')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [74]:
# 전체
pd.merge(df7, df8, how = 'outer')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN
3  김유신  NaN   커피

In [75]:
# df7 기준
pd.merge(df7, df8, how = 'left')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN

In [76]:
# df8 기준
pd.merge(df7, df8, how = 'right')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  김유신  NaN   커피

In [77]:
df9 = pd.DataFrame({'이름' : ['홍길동', '이순신', '임꺽정', '김유신'],
                   '순위' : [3, 2, 4, 1]})
df9

이름  순위
0  홍길동   3
1  이순신   2
2  임꺽정   4
3  김유신   1

In [78]:
df10 = pd.DataFrame({'이름' : ['홍길동', '이순신', '임꺽정', '김유신'],
                   '순위' : [4, 1, 3, 2]})
df10

이름  순위
0  홍길동   4
1  이순신   1
2  임꺽정   3
3  김유신   2

In [80]:
pd.merge(df9, df10, on = '이름')

이름  순위_x  순위_y
0  홍길동     3     4
1  이순신     2     1
2  임꺽정     4     3
3  김유신     1     2

In [81]:
pd.merge(df9, df10, on = '이름', suffixes = ['_인기', '_성적'])

이름  순위_인기  순위_성적
0  홍길동      3      4
1  이순신      2      1
2  임꺽정      4      3
3  김유신      1      2

- 데이터 집계와 그룹연산

    - 집계연산(Aggregation)

In [82]:
df = pd.DataFrame([[1, 1.2, np.nan],
                  [2.4, 5.5, 4.2],
                  [np.nan, np.nan, np.nan],
                  [0.44, -3.1, -4.1]],
                 index = [1, 2, 3, 4],
                 columns = ['A', 'B', 'C'])
df

A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [84]:
df.head(2)

A    B    C
1  1.0  1.2  NaN
2  2.4  5.5  4.2

In [85]:
df.tail(2)

A    B    C
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [88]:
df.describe()

A     B         C
count  3.000000  3.00  2.000000
mean   1.280000  1.20  0.050000
std    1.009554  4.30  5.868986
min    0.440000 -3.10 -4.100000
25%    0.720000 -0.95 -2.025000
50%    1.000000  1.20  0.050000
75%    1.700000  3.35  2.125000
max    2.400000  5.50  4.200000

In [91]:
print(df)
print(np.argmin(df), np.argmax(df))

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
2 2


In [92]:
print(df)
print(df.idxmin())
print(df.idxmax())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    4
B    4
C    4
dtype: int64
A    2
B    2
C    2
dtype: int64


In [93]:
print(df)
print(df.std())
print(df.var())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.009554
B    4.300000
C    5.868986
dtype: float64
A     1.0192
B    18.4900
C    34.4450
dtype: float64


In [94]:
print(df)
# 왜도
print(df.skew())
# 첨도
print(df.kurt())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.15207
B    0.00000
C        NaN
dtype: float64
A   NaN
B   NaN
C   NaN
dtype: float64


In [96]:
print(df)
print(df.sum())
# 누적 합 
print(df.cumsum())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    3.84
B    3.60
C    0.10
dtype: float64
      A    B    C
1  1.00  1.2  NaN
2  3.40  6.7  4.2
3   NaN  NaN  NaN
4  3.84  3.6  0.1


In [97]:
print(df)
print(df.prod())
# 누적 곱
print(df.cumprod())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A     1.056
B   -20.460
C   -17.220
dtype: float64
       A      B      C
1  1.000   1.20    NaN
2  2.400   6.60   4.20
3    NaN    NaN    NaN
4  1.056 -20.46 -17.22


In [98]:
# 차
df.diff()

A    B   C
1  NaN  NaN NaN
2  1.4  4.3 NaN
3  NaN  NaN NaN
4  NaN  NaN NaN

In [101]:
df.quantile()

A    1.00
B    1.20
C    0.05
Name: 0.5, dtype: float64

In [102]:
df.pct_change()

A         B        C
1       NaN       NaN      NaN
2  1.400000  3.583333      NaN
3  0.000000  0.000000  0.00000
4 -0.816667 -1.563636 -1.97619

In [103]:
df.corr()

A         B    C
A  1.000000  0.970725  1.0
B  0.970725  1.000000  1.0
C  1.000000  1.000000  1.0

In [104]:
df.corrwith(df.B)

A    0.970725
B    1.000000
C    1.000000
dtype: float64

In [105]:
# 공분산
df.cov()

A       B       C
A  1.0192   4.214   8.134
B  4.2140  18.490  35.690
C  8.1340  35.690  34.445

In [106]:
df['B'].unique()

array([ 1.2,  5.5,  nan, -3.1])

In [108]:
df.value_counts('A')

A   
0.44    1
1.00    1
2.40    1
dtype: int64

    - Groupby 연산

In [117]:
df = pd.DataFrame({'c1' : ['a', 'a', 'b', 'b', 'c', 'd', 'b'],
                  'c2' : ['A', 'B', 'B', 'A', 'D', 'C', 'C'],
                  'c3' : np.random.randint(7),
                  'c4' : np.random.random(7)})
df

c1 c2  c3        c4
0  a  A   3  0.475233
1  a  B   3  0.466524
2  b  B   3  0.486081
3  b  A   3  0.075909
4  c  D   3  0.978359
5  d  C   3  0.191600
6  b  C   3  0.158732

In [118]:
df.dtypes

c1     object
c2     object
c3      int64
c4    float64
dtype: object

In [119]:
# 'c1'열을 기준으로 'c4'의 평균
df['c4'].groupby(df['c1']).mean()

c1
a    0.470878
b    0.240241
c    0.978359
d    0.191600
Name: c4, dtype: float64

In [120]:
df['c4'].groupby(df['c2']).std()

c2
A    0.282364
B    0.013829
C    0.023242
D         NaN
Name: c4, dtype: float64

In [121]:
df['c4'].groupby([df['c1'], df['c2']]).mean()

c1  c2
a   A     0.475233
    B     0.466524
b   A     0.075909
    B     0.486081
    C     0.158732
c   D     0.978359
d   C     0.191600
Name: c4, dtype: float64

In [122]:
df['c4'].groupby([df['c1'], df['c2']]).mean().unstack()

c2         A         B         C         D
c1                                        
a   0.475233  0.466524       NaN       NaN
b   0.075909  0.486081  0.158732       NaN
c        NaN       NaN       NaN  0.978359
d        NaN       NaN  0.191600       NaN

In [123]:
df.groupby('c1').mean()

c3        c4
c1              
a    3  0.470878
b    3  0.240241
c    3  0.978359
d    3  0.191600

In [124]:
df.groupby(['c1', 'c2']).mean()

c3        c4
c1 c2              
a  A    3  0.475233
   B    3  0.466524
b  A    3  0.075909
   B    3  0.486081
   C    3  0.158732
c  D    3  0.978359
d  C    3  0.191600

In [125]:
df.groupby(['c1', 'c2']).size()

c1  c2
a   A     1
    B     1
b   A     1
    B     1
    C     1
c   D     1
d   C     1
dtype: int64

In [126]:
for c1, group in df.groupby('c1'):
    print(c1)
    print(group)

a
  c1 c2  c3        c4
0  a  A   3  0.475233
1  a  B   3  0.466524
b
  c1 c2  c3        c4
2  b  B   3  0.486081
3  b  A   3  0.075909
6  b  C   3  0.158732
c
  c1 c2  c3        c4
4  c  D   3  0.978359
d
  c1 c2  c3      c4
5  d  C   3  0.1916


In [128]:
for (c1, c2), group in df.groupby(['c1', 'c2']):
    print((c1, c2))
    print(group)

('a', 'A')
  c1 c2  c3        c4
0  a  A   3  0.475233
('a', 'B')
  c1 c2  c3        c4
1  a  B   3  0.466524
('b', 'A')
  c1 c2  c3        c4
3  b  A   3  0.075909
('b', 'B')
  c1 c2  c3        c4
2  b  B   3  0.486081
('b', 'C')
  c1 c2  c3        c4
6  b  C   3  0.158732
('c', 'D')
  c1 c2  c3        c4
4  c  D   3  0.978359
('d', 'C')
  c1 c2  c3      c4
5  d  C   3  0.1916


In [129]:
df.groupby(['c1', 'c2'])[['c4']].mean()

c4
c1 c2          
a  A   0.475233
   B   0.466524
b  A   0.075909
   B   0.486081
   C   0.158732
c  D   0.978359
d  C   0.191600

In [136]:
df.groupby('c1')['c4'].count()

c1
a    2
b    3
c    1
d    1
Name: c4, dtype: int64

In [134]:
df.groupby('c1')['c4'].median()

c1
a    0.470878
b    0.158732
c    0.978359
d    0.191600
Name: c4, dtype: float64

In [135]:
df.groupby('c1')['c4'].std()

c1
a    0.006158
b    0.216894
c         NaN
d         NaN
Name: c4, dtype: float64

In [137]:
df.groupby(['c1', 'c2'])['c4'].agg(['mean', 'min', 'max'])

mean       min       max
c1 c2                              
a  A   0.475233  0.475233  0.475233
   B   0.466524  0.466524  0.466524
b  A   0.075909  0.075909  0.075909
   B   0.486081  0.486081  0.486081
   C   0.158732  0.158732  0.158732
c  D   0.978359  0.978359  0.978359
d  C   0.191600  0.191600  0.191600

In [138]:
# 'as_index = False' index 값 표시 X
df.groupby(['c1', 'c2'], as_index = False)['c4'].mean()

c1 c2        c4
0  a  A  0.475233
1  a  B  0.466524
2  b  A  0.075909
3  b  B  0.486081
4  b  C  0.158732
5  c  D  0.978359
6  d  C  0.191600

In [140]:
df.groupby(['c1', 'c2'], group_keys = False)['c4'].mean()

c1  c2
a   A     0.475233
    B     0.466524
b   A     0.075909
    B     0.486081
    C     0.158732
c   D     0.978359
d   C     0.191600
Name: c4, dtype: float64

In [141]:
def top(df, n=3, column = 'c1'):
    return df.sort_values(by = column)[-n:]

top(df, n=5)

c1 c2  c3        c4
2  b  B   3  0.486081
3  b  A   3  0.075909
6  b  C   3  0.158732
4  c  D   3  0.978359
5  d  C   3  0.191600

In [142]:
df.groupby('c1').apply(top)

c1 c2  c3        c4
c1                      
a  0  a  A   3  0.475233
   1  a  B   3  0.466524
b  2  b  B   3  0.486081
   3  b  A   3  0.075909
   6  b  C   3  0.158732
c  4  c  D   3  0.978359
d  5  d  C   3  0.191600

- 피벗 테이블(Pivot Table)

In [143]:
df.pivot_table(['c3', 'c4'],
              index = ['c1'],
              columns = ['c2'])


c3                       c4                              
c2    A    B    C    D         A         B         C         D
c1                                                            
a   3.0  3.0  NaN  NaN  0.475233  0.466524       NaN       NaN
b   3.0  3.0  3.0  NaN  0.075909  0.486081  0.158732       NaN
c   NaN  NaN  NaN  3.0       NaN       NaN       NaN  0.978359
d   NaN  NaN  3.0  NaN       NaN       NaN  0.191600       NaN

In [144]:
df.pivot_table(['c3', 'c4'],
              index = ['c1'],
              columns = ['c2'],
              margins = True)

# 'margins' : 부분합 ['All']  총계

c3                           c4                                        
c2     A    B    C    D All         A         B         C         D       All
c1                                                                           
a    3.0  3.0  NaN  NaN   3  0.475233  0.466524       NaN       NaN  0.470878
b    3.0  3.0  3.0  NaN   3  0.075909  0.486081  0.158732       NaN  0.240241
c    NaN  NaN  NaN  3.0   3       NaN       NaN       NaN  0.978359  0.978359
d    NaN  NaN  3.0  NaN   3       NaN       NaN  0.191600       NaN  0.191600
All  3.0  3.0  3.0  3.0   3  0.275571  0.476302  0.175166  0.978359  0.404634

In [145]:
df.pivot_table(['c3', 'c4'],
              index = ['c1'],
              columns = ['c2'],
              margins = True,
              aggfunc = sum)

c3                           c4                                        
c2     A    B    C    D All         A         B         C         D       All
c1                                                                           
a    3.0  3.0  NaN  NaN   6  0.475233  0.466524       NaN       NaN  0.941757
b    3.0  3.0  3.0  NaN   9  0.075909  0.486081  0.158732       NaN  0.720722
c    NaN  NaN  NaN  3.0   3       NaN       NaN       NaN  0.978359  0.978359
d    NaN  NaN  3.0  NaN   3       NaN       NaN  0.191600       NaN  0.191600
All  6.0  6.0  6.0  3.0  21  0.551142  0.952605  0.350332  0.978359  2.832437

In [146]:
df.pivot_table(['c3', 'c4'],
              index = ['c1'],
              columns = ['c2'],
              margins = True,
              aggfunc = sum,
              fill_value = 0)

c3                     c4                                        
c2   A  B  C  D All         A         B         C         D       All
c1                                                                   
a    3  3  0  0   6  0.475233  0.466524  0.000000  0.000000  0.941757
b    3  3  3  0   9  0.075909  0.486081  0.158732  0.000000  0.720722
c    0  0  0  3   3  0.000000  0.000000  0.000000  0.978359  0.978359
d    0  0  3  0   3  0.000000  0.000000  0.191600  0.000000  0.191600
All  6  6  6  3  21  0.551142  0.952605  0.350332  0.978359  2.832437

In [147]:
pd.crosstab(df.c1, df.c2)

c2  A  B  C  D
c1            
a   1  1  0  0
b   1  1  1  0
c   0  0  0  1
d   0  0  1  0

In [148]:
pd.crosstab(df.c1, df.c2, values = df.c3, aggfunc = sum, margins = True)

c2     A    B    C    D  All
c1                          
a    3.0  3.0  NaN  NaN    6
b    3.0  3.0  3.0  NaN    9
c    NaN  NaN  NaN  3.0    3
d    NaN  NaN  3.0  NaN    3
All  6.0  6.0  6.0  3.0   21

- 범주형(Categorical) 데이터

In [149]:
s = pd.Series(['c1', 'c2', 'c1', 'c2', 'c1'] * 2)
s

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
dtype: object

In [152]:
pd.unique(s)

array(['c1', 'c2'], dtype=object)

In [153]:
s.value_counts()

c1    6
c2    4
dtype: int64

In [154]:
code = pd.Series([0, 1, 0, 1,0] * 2)
code

0    0
1    1
2    0
3    1
4    0
5    0
6    1
7    0
8    1
9    0
dtype: int64

In [155]:
d = pd.Series(['c1', 'c2'])
d

0    c1
1    c2
dtype: object

In [156]:
d.take(code)

0    c1
1    c2
0    c1
1    c2
0    c1
0    c1
1    c2
0    c1
1    c2
0    c1
dtype: object

In [159]:
df = pd.DataFrame({'id' : np.arange(len(s)),
                 'c' : s,
                 'v' : np.random.randint(1000, 5000, size = len(s))})
df

id   c     v
0   0  c1  4791
1   1  c2  2182
2   2  c1  1296
3   3  c2  2462
4   4  c1  4961
5   5  c1  1095
6   6  c2  1385
7   7  c1  4988
8   8  c2  1442
9   9  c1  4617

In [160]:
c = df['c'].astype('category')
c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [161]:
c.values

['c1', 'c2', 'c1', 'c2', 'c1', 'c1', 'c2', 'c1', 'c2', 'c1']
Categories (2, object): ['c1', 'c2']

In [163]:
c.values.categories

Index(['c1', 'c2'], dtype='object')

In [164]:
c.values.codes

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int8)

In [165]:
df['c'] = c
df.c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [166]:
c = pd.Categorical(['c1', 'c2', 'c3', 'c1', 'c2'])
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [167]:
categories = ['c1', 'c2', 'c3']
codes = [0, 1, 2, 0, 1]
c = pd.Categorical.from_codes(codes, categories)
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [169]:
# 순서
pd.Categorical.from_codes(codes, categories, ordered = True)

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [170]:
c.as_ordered()

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [171]:
c.codes

array([0, 1, 2, 0, 1], dtype=int8)

In [172]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')

In [173]:
c = c.set_categories(['c1', 'c2', 'c3', 'c4', 'c5'])
c.categories

Index(['c1', 'c2', 'c3', 'c4', 'c5'], dtype='object')

In [174]:
c.value_counts()

c1    2
c2    2
c3    1
c4    0
c5    0
dtype: int64

In [175]:
c[c.isin(['c1', 'c3'])]

['c1', 'c3', 'c1']
Categories (5, object): ['c1', 'c2', 'c3', 'c4', 'c5']

In [176]:
c = c.remove_unused_categories()

In [177]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')