# 자연어 처리(Natural Language Processing)

* 자연어는 일상 생활에서 사용하는 언어
* 자연어 처리는 자연어의 의미를 분석 처리하는 일
* 텍스트 분류, 감성 분석, 문서 요약, 번역, 질의 응답, 음성 인식, 챗봇과 같은 응용

## 텍스트 처리

In [5]:
s = 'No pain no gain'

In [6]:
'pain' in s

True

In [7]:
s.split()

['No', 'pain', 'no', 'gain']

In [8]:
s.split().index('gain')

3

In [9]:
s[-4:]

'gain'

In [10]:
s.split()[1]

'pain'

In [11]:
# 글자 'no'를 거꾸로 slicing >> 'on' 출력
s.split()[2][::-1]

'on'

In [12]:
s = "한글도 처리 가능"

In [13]:
"처리" in s

True

In [14]:
s.split()

['한글도', '처리', '가능']

In [15]:
s.split()[0]

'한글도'

## 영어 처리

#### 대소문자 통합

* 대소문자를 통합하지 않는다면 컴퓨터는 같은 단어를 다르게 받아들임
* 파이썬의 내장 함수 `lower()`, `upper()`를 통해 간단하게 통합 가능

In [16]:
s = 'AbCdEfGh'
str_lower = s.lower()
str_upper = s.upper()

print(str_lower, str_upper)

abcdefgh ABCDEFGH


### 정규화(Normalization)

In [17]:
s = "I visited UK from US on 22-09-20"
print(s)

I visited UK from US on 22-09-20


In [19]:
new_s = s.replace("UK", "United Kingdom").replace("US", "United States").replace("-20", "-2020")
print(new_s)

I visited United Kingdom from United States on 22-09-2020


### 정규표현식

* 정규 표현식은 특정 문자들을 편리하게 지정하고 추가, 삭제 가능
* 데이터 전처리에서 정규 표현식을 많이 사용
* 파이썬에서는 정규 표현식을 지원하는 `re` 패키지 제공

* 정규 표현식 문법
  
| 특수문자 | 설명 |
| - | - |
| `.` | 앞의 문자 1개를 표현 |
| `?` | 문자 한개를 표현하나 존재할 수도, 존재하지 않을 수도 있음(0개 또는 1개) |
| `*` | 앞의 문자가 0개 이상 |
| `+` | 앞의 문자가 최소 1개 이상 |
| `^` | 뒤의 문자로 문자열이 시작 |
| `\$` | 앞의 문자로 문자열이 끝남 |
| `\{n\}` | `n`번만큼 반복 |
| `\{n1, n2\}` | `n1` 이상, `n2` 이하만큼 반복, n2를 지정하지 않으면 `n1` 이상만 반복 |
| `\[ abc \]` | 안에 문자들 중 한 개의 문자와 매치, a-z처럼 범위도 지정 가능 |
| `\[ ^a \]` | 해당 문자를 제외하고 매치 |
| `a\|b` | `a` 또는 `b`를 나타냄 |

* 정규 표현식에 자주 사용하는 역슬래시(\\)를 이용한 문자 규칙

| 문자 | 설명 |
| - | - |
| `\\` | 역슬래시 자체를 의미 |
| `\d` | 모든 숫자를 의미, [0-9]와 동일 |
| `\D` | 숫자를 제외한 모든 문자를 의미, [^0-9]와 동일 |
| `\s` | 공백을 의미, [ \t\n\r\f\v]와 동일|
| `\S` | 공백을 제외한 모든 문자를 의미, [^ \t\n\r\f\v]와 동일 |
| `\w` | 문자와 숫자를 의미, [a-zA-Z0-9]와 동일 |
| `\W` | 문자와 숫자를 제외한 다른 문자를 의미, [^a-zA-Z0-9]와 동일 |

#### match

* 컴파일한 정규 표현식을 이용해 문자열이 정규 표현식과 맞는지 검사

In [20]:
import re

In [23]:
check = 'ab.'

print(re.match(check, 'abc'))
print(re.match(check, 'c'))
print(re.match(check, 'ab'))
print(re.match(check, 'abcd'))

<re.Match object; span=(0, 3), match='abc'>
None
None
<re.Match object; span=(0, 3), match='abc'>


#### compile

* compile을 사용하면 여러 번 사용할 경우 일반 사용보다 더 빠른 속도를 보임
* compile을 통해 정규 표현식을 사용할 경우 `re`가 아닌 컴파일한 객체 이름을 통해 사용해야 함


In [24]:
import time

normal_s_time = time.time()
r = 'ab.'

for i in range(1000):
    re.match(check, 'abc')
    
print('일반 사용 소요시간: ', time.time() - normal_s_time)

compile_s_time = time.time()
r = re.compile('ab.')

for i in range(1000):
    r.match(check)
    
print('컴파일 사용 소요시간: ', time.time() - compile_s_time) # 더 짧다

일반 사용 소요시간:  0.0
컴파일 사용 소요시간:  0.0


#### search

* match와 다르게, search는 문자열의 전체를 검사

In [27]:
check = 'ab?'

print(re.search('a', check))
print(re.match('kkkab', check))
print(re.search('kkkab', check))
print(re.match('ab', check))

<re.Match object; span=(0, 1), match='a'>
None
None
<re.Match object; span=(0, 2), match='ab'>


#### split

* 정규표현식에 해당하는 문자열을 기준으로 문자열을 나눔

In [28]:
r = re.compile(' ')
print(r.split('abc abbc abcbab'))

r = re.compile('c')
print(r.split('abc abbc abcbab'))

r = re.compile('[1-9]')
print(r.split('s1abc 2v3s 4sss 5a'))

['abc', 'abbc', 'abcbab']
['ab', ' abb', ' ab', 'bab']
['s', 'abc ', 'v', 's ', 'sss ', 'a']


#### sub

* 정규 표현식과 일치하는 부분을 다른 문자열로 교체


In [29]:
print(re.sub('[a-z]', 'abcdefg', '1'))

print(re.sub('[^a-z]', 'abc defg', '1'))

1
abc defg


#### findall

* 컴파일한 정규 표현식을 이용해 정규 표현식과 맞는 모든 문자(열)을 리스트로 반환


In [30]:
print(re.findall('[\d]', '1ab 2cd 3ef 4g'))

print(re.findall('[\W]', '!abcd@@#'))

['1', '2', '3', '4']
['!', '@', '@', '#']


#### finditer

* 컴파일한 정규 표현식을 이용해 정규 표현식과 맞는 모든 문자(열)을 `iterator` 객체로 반환
* `iterator` 객체를 이용하면 생성된 객체를 하나씩 자동으로 가져올 수 있어 처리가 간편함

In [31]:
iter1 = re.finditer('[\d]', '1ab 2cd 3ef 4g')
print(iter1)

for i in iter1:
    print(i)
    
iter2 = re.finditer('[\W]', '!abcd@@#')
print(iter2)

for i in iter2:
    print(i)

<re.Match object; span=(0, 1), match='1'>
<re.Match object; span=(4, 5), match='2'>
<re.Match object; span=(8, 9), match='3'>
<re.Match object; span=(12, 13), match='4'>
<re.Match object; span=(0, 1), match='!'>
<re.Match object; span=(5, 6), match='@'>
<re.Match object; span=(6, 7), match='@'>
<re.Match object; span=(7, 8), match='#'>


### 토큰화(Tokenization)

* 특수문자에 대한 처리

  + 단어에 일반적으로 사용되는 알파벳, 숫자와는 다르게 특수문자는 별도의 처리가 필요            
  + 일괄적으로 단어의 특수문자를 제거하는 방법도 있지만 특수문자가 단어에 특별한 의미를 가질 때 이를 학습에 반영시키지 못할 수도 있음
  + 특수문자에 대한 일괄적인 제거보다는 데이터의 특성을 파악하고, 처리를 하는 것이 중요


* 특정 단어에 대한 토큰 분리 방법

  + 한 단어지만 토큰으로 분리할 때 판단되는 문자들로 이루어진 we're, United Kingdom 등의 단어는 어떻게 분리해야 할지 선택이 필요   
  + we're은 한 단어이나 분리해도 단어의 의미에 별 영향을 끼치진 않지만 United Kingdom은 두 단어가 모여 특정 의미를 가리켜 분리해선 안됨
  + 사용자가 단어의 특성을 고려해 토큰을 분리하는 것이 학습에 유리

#### 단어 토큰화

* 파이썬 내장 함수인 `split`을 활용해 단어 토큰화
* 공백을 기준으로 단어를 분리

In [34]:
sentence = 'Time is gold'
tokens = [x for x in sentence.split(' ')]
tokens

['Time', 'is', 'gold']

* 토큰화는 `nltk` 패키지의 `tokenize` 모듈을 사용해 손쉽게 구현 가능
* 단어 토큰화는 `word_tokenize()` 함수를 사용해 구현 가능

In [36]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [38]:
from nltk.tokenize import word_tokenize

tokens = word_tokenize(sentence)
tokens

['Time', 'is', 'gold']

#### 문장 토큰화

* 문장 토큰화는 줄바꿈 문자('\n')를 기준으로 문장을 분리

In [39]:
sentences = 'The word is a beautiful book.\nBut of little use to him who cannot read it.'
print(sentences)

toknes = [x for x in sentences.split('\n')]
toknes

The word is a beautiful book.
But of little use to him who cannot read it.


['The word is a beautiful book.',
 'But of little use to him who cannot read it.']

In [40]:
toknes[1]

'But of little use to him who cannot read it.'

* 문장 토큰화는 `sent_tokenize()` 함수를 사용해 구현 가능

In [42]:
from nltk.tokenize import sent_tokenize

tokens = sent_tokenize(sentences)
tokens

['The word is a beautiful book.',
 'But of little use to him who cannot read it.']

* 문장 토큰화에서는 온점(.)의 처리를 위해 이진 분류기를 사용할 수도 있음
* 온점은 문장과 문장을 구분해줄 수도, 문장에 포함된 단어를 구성할 수도 있기 때문에 이를 이진 분류기로 분류해 더욱 좋은 토큰화를 구현할 수도 있음

#### 정규 표현식을 이용한 토큰화

* 토큰화 기능을 직접 구현할 수도 있지만 정규 표현식을 이용해 간단하게 구현할 수도 있음
* `nltk` 패키지는 정규 표현식을 사용하는 토큰화 도구인 `RegexpTokenizer`를 제공

In [44]:
from nltk.tokenize import RegexpTokenizer

sentence = 'Where there\'s a will, there\'s a way'

tokenizer = RegexpTokenizer("[\w]+")
tokens = tokenizer.tokenize(sentence)
tokens

['Where', 'there', 's', 'a', 'will', 'there', 's', 'a', 'way']

In [45]:
tokenizer = RegexpTokenizer("[\s]+", gaps = True)  # 특수문자를 남기고, 공백을 기준으로 tokenize
tokens = tokenizer.tokenize(sentence)
tokens

['Where', "there's", 'a', 'will,', "there's", 'a', 'way']

#### 케라스를 이용한 토큰화

In [46]:
from keras.preprocessing.text import text_to_word_sequence

sentence = 'Where there\'s a will, there\'s a way'

text_to_word_sequence(sentence)

['where', "there's", 'a', 'will', "there's", 'a', 'way']

#### TextBlob을 이용한 토큰화

In [49]:
from textblob import TextBlob

sentence = 'Where there\'s a will, there\'s a way'

blob = TextBlob(sentence)
blob.words

WordList(['Where', 'there', "'s", 'a', 'will', 'there', "'s", 'a', 'way'])

#### 기타 토크나이저

* WhiteSpaceTokenizer: 공백을 기준으로 토큰화
* WordPunktTokenizer: 텍스트를 알파벳 문자, 숫자, ㅇ라파벳 이외의 문자 리스트로 토큰화
* MWETokenizer: MWE는 Multi-Word Expression의 약자로 'republic of korea'와 같이 여러 단어로 이뤄진 특정 그룹을 한 개체로 취급
* TweetTokenizer: 트위터에서 사용되는 문장의 토큰화를 위해서 만들어졌으며, 문장 속 감성의 표현과 감정을 다룸

### n-gram 추출

* n-gram은 n개의 어절이나 음절을 연쇄적으로 분류해 그 빈도를 분석
* n=1일 때는 unigram, n=2일 때는 bigram, n=3일 때는 trigram으로 불림

In [50]:
from nltk import ngrams

sentence = 'There is no royal read to learning'
bigram = list(ngrams(sentence.split(), 2))
print(bigram)

[('There', 'is'), ('is', 'no'), ('no', 'royal'), ('royal', 'read'), ('read', 'to'), ('to', 'learning')]


In [51]:
trigram = list(ngrams(sentence.split(), 3))
print(trigram)

[('There', 'is', 'no'), ('is', 'no', 'royal'), ('no', 'royal', 'read'), ('royal', 'read', 'to'), ('read', 'to', 'learning')]


In [52]:
from textblob import TextBlob

blob = TextBlob(sentence)
blob.ngrams(n = 2)

[WordList(['There', 'is']),
 WordList(['is', 'no']),
 WordList(['no', 'royal']),
 WordList(['royal', 'read']),
 WordList(['read', 'to']),
 WordList(['to', 'learning'])]

In [53]:
blob.ngrams(n = 3)

[WordList(['There', 'is', 'no']),
 WordList(['is', 'no', 'royal']),
 WordList(['no', 'royal', 'read']),
 WordList(['royal', 'read', 'to']),
 WordList(['read', 'to', 'learning'])]

### PoS(Parts of Speech) 태깅 

* PoS는 품사를 의미하며, PoS 태깅은 문장 내에서 단어에 해당하는 각 품사를 태깅

In [54]:
import nltk
nltk.download('punkt')

from nltk import word_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [56]:
words = word_tokenize('Think like man of action and act like man of thought.')
words

['Think',
 'like',
 'man',
 'of',
 'action',
 'and',
 'act',
 'like',
 'man',
 'of',
 'thought',
 '.']

In [58]:
nltk.download('averaged_perceptron_tagger')

nltk.pos_tag(words)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


[('Think', 'VBP'),
 ('like', 'IN'),
 ('man', 'NN'),
 ('of', 'IN'),
 ('action', 'NN'),
 ('and', 'CC'),
 ('act', 'NN'),
 ('like', 'IN'),
 ('man', 'NN'),
 ('of', 'IN'),
 ('thought', 'NN'),
 ('.', '.')]

In [59]:
nltk.pos_tag(word_tokenize('A rolling stone gathers no moss'))

[('A', 'DT'),
 ('rolling', 'VBG'),
 ('stone', 'NN'),
 ('gathers', 'NNS'),
 ('no', 'DT'),
 ('moss', 'NN')]

* PoS 태그 리스트

| Number | Tag | Description | 설명 |
| -- | -- | -- | -- |
| 1 | `CC` | Coordinating conjunction |
| 2 | `CD` | Cardinal number |
| 3 | `DT` | Determiner | 한정사
| 4 | `EX` | Existential there |
| 5 | `FW` | Foreign word | 외래어 |
| 6 | `IN` | Preposition or subordinating conjunction | 전치사 또는 종속 접속사 |
| 7 | `JJ` | Adjective | 형용사 |
| 8 | `JJR` | Adjective, comparative | 헝용사, 비교급 |
| 9 | `JJS` | Adjective, superlative | 형용사, 최상급 |
| 10 | `LS` | List item marker |
| 11 | `MD` | Modal |
| 12 | `NN` | Noun, singular or mass | 명사, 단수형 |
| 13 | `NNS` | Noun, plural | 명사, 복수형 |
| 14 | `NNP` | Proper noun, singular | 고유명사, 단수형 |
| 15 | `NNPS` | Proper noun, plural | 고유명사, 복수형 |
| 16 | `PDT` | Predeterminer | 전치한정사 |
| 17 | `POS` | Possessive ending | 소유형용사 |
| 18 | `PRP` | Personal pronoun | 인칭 대명사 |
| 19 | `PRP$` | Possessive pronoun | 소유 대명사 |
| 20 | `RB` | Adverb | 부사 |
| 21 | `RBR` | Adverb, comparative | 부사, 비교급 |
| 22 | `RBS` | Adverb, superlative | 부사, 최상급 |
| 23 | `RP` | Particle |
| 24 | `SYM` | Symbol | 기호
| 25 | `TO` | to |
| 26 | `UH` | Interjection | 감탄사 |
| 27 | `VB` | Verb, base form | 동사, 원형 |
| 28 | `VBD` | Verb, past tense | 동사, 과거형 |
| 29 | `VBG` | Verb, gerund or present participle | 동사, 현재분사 |
| 30 | `VBN` | Verb, past participle | 동사, 과거분사 |
| 31 | `VBP` | Verb, non-3rd person singular present | 동사, 비3인칭 단수 |
| 32 | `VBZ` | Verb, 3rd person singular present | 동사, 3인칭 단수 |
| 33 | `WDT` | Wh-determiner |
| 34 | `WP` | Wh-pronoun |
| 35 | `WP$` | Possessive wh-pronoun |
| 36 | `WRB` | Wh-adverb |


### 불용어 제거

* 영어의 전치사(on, in), 한국어의 조사(을, 를) 등은 분석에 필요하지 않은 경우가 많음
* 길이가 짧은 단어, 등장 빈도 수가 적은 단어들도 분석에 큰 영향을 주지 않음
* 일반적으로 사용되는 도구들은 해당 단어들을 제거해주지만 완벽하게 제거되지는 않음
* 사용자가 불용어(Stopword) 사전을 만들어 해당 단어들을 제거하는 것이 좋음
* 도구들이 걸러주지 않는 전치사, 조사 등을 불용어 사전을 만들어 불필요한 단어들을 제거


In [60]:
stop_words = 'on in the'
stop_words = stop_words.split(' ')
stop_words

['on', 'in', 'the']

In [61]:
sentence = 'singer on the stage'
sentence = sentence.split(' ')
nouns = []

for noun in sentence:
    if noun not in stop_words:
        nouns.append(noun)
        
nouns

['singer', 'stage']

* `nltk` 패키지에 불용어 리스트 사용

In [62]:
import nltk
nltk.download('stopwords')

from nltk import word_tokenize
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [63]:
stop_words = stopwords.words('english')
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [64]:
s = 'If you do not walk today, you will have to run tomorrow.'
words = word_tokenize(s)
print(words)

['If', 'you', 'do', 'not', 'walk', 'today', ',', 'you', 'will', 'have', 'to', 'run', 'tomorrow', '.']


In [65]:
no_stopwords = []

for w in words:
    if w not in stop_words:
        no_stopwords.append(w)
        
print(no_stopwords)

['If', 'walk', 'today', ',', 'run', 'tomorrow', '.']


### 철자 교정

* 텍스트에 오탈자가 존재하는 경우가 있음
* 예를 들어, 단어 'apple'을 'aplpe'과 같이 철자 순서가 바뀌거나 spple 같이 철자가 틀릴 수 있음
* 사람이 적절한 추정을 통해 이해하는데는 문제가 없지만, 컴퓨터는 이러한 단어를 그대로 받아들여 처리가 필요
* 철자 교정 알고리즘은 이미 개발되어 워드 프로세서나 다양한 서비스에서 많이 적용됨
됨

In [67]:
from autocorrect import Speller

In [69]:
spell = Speller('en')

print(spell('peoplle'))
print(spell('peope'))
print(spell('peopae'))

people
people
people


In [70]:
s = word_tokenize('Earlly biird catchess the womm.')
print(s)
ss = ' '.join([spell(s) for s in s])
print(ss)

['Earlly', 'biird', 'catchess', 'the', 'womm', '.']
Early bird catches the worm .


### 언어의 단수화와 복수화

In [71]:
from textblob import TextBlob

words = 'apples bananas oranges'
tb = TextBlob(words)

print(tb.words)
print(tb.words.singularize())

['apples', 'bananas', 'oranges']
['apple', 'banana', 'orange']


In [72]:
words = 'car train airplane'
tb = TextBlob(words)

print(tb.words)
print(tb.words.pluralize())

['car', 'train', 'airplane']
['cars', 'trains', 'airplanes']


### 어간(Stemming) 추출

In [75]:
import nltk

stemmer = nltk.stem.PorterStemmer()

In [76]:
stemmer.stem('application')

'applic'

In [77]:
stemmer.stem('beginning')

'begin'

In [78]:
stemmer.stem('catches')

'catch'

In [79]:
stemmer.stem('education')

'educ'

### 표제어(Lemmatization) 추출

In [80]:
import nltk
nltk.download('wordnet')
from nltk.stem.wordnet import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


In [81]:
lemmatizer.lemmatize('application')

'application'

In [82]:
lemmatizer.lemmatize('beginning')

'beginning'

In [83]:
lemmatizer.lemmatize('catches')

'catch'

In [84]:
lemmatizer.lemmatize('education')

'education'

### 개체명 인식(Named Entity Recognition)



In [85]:
import nltk
from nltk import word_tokenize
nltk.download('maxent_ne_chunker')
nltk.download('words')

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping chunkers\maxent_ne_chunker.zip.
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\words.zip.


True

In [86]:
s = "Rome was not built in a day."
print(s)

Rome was not built in a day.


In [87]:
tags = nltk.pos_tag(word_tokenize(s))
print(tags)

[('Rome', 'NNP'), ('was', 'VBD'), ('not', 'RB'), ('built', 'VBN'), ('in', 'IN'), ('a', 'DT'), ('day', 'NN'), ('.', '.')]


In [88]:
entities = nltk.ne_chunk(tags, binary = True)
print(entities)

(S (NE Rome/NNP) was/VBD not/RB built/VBN in/IN a/DT day/NN ./.)


### 단어 중의성(Lexical Ambiguity)

In [89]:
import nltk
from nltk.wsd import lesk

s = "I saw  bats."
# 해석 1. 난 박쥐를 보았다.
# 해석 2. 난 (톱을 이용해) 야구방망이를 갈았다.
# 해석 3. 난 야구방망이를 보았다. .....

print(word_tokenize(s))
print(lesk(word_tokenize(s), 'saw'))  # v : verb
print(lesk(word_tokenize(s), 'bats'))  # n : noun

['I', 'saw', 'bats', '.']
Synset('saw.v.01')
Synset('squash_racket.n.01')


## 한국어 처리

### 정규표현식

* 한국어 정규 표현식도 대부분의 문법은 영어 정규 표현식과 같음
* 한국어는 자음과 모음이 분리되어 있기 때문에, 문법을 지정할 때는 자음과 모음을 동시에 고려해야 함

#### match

* 컴파일한 정규 표현식을 이용해 문자열이 정규 표현식과 맞는지 검사

In [90]:
import re

check = '[ㄱ-ㅎ]+'

print(re.match(check, 'ㅎ 안녕하세요.'))
print(re.match(check, '안녕하세요. ㅎ'))

<re.Match object; span=(0, 1), match='ㅎ'>
None


#### search

* match와 다르게, search는 문자열의 전체를 검사

In [91]:
check = '[ㄱ-ㅎ|ㅏ-ㅣ]+'

print(re.search(check, 'ㄱㅏ 안녕하세요'))
print(re.match(check, '안 ㄱㅏ'))
print(re.search(check, '안 ㄱㅏ'))

<re.Match object; span=(0, 2), match='ㄱㅏ'>
None
<re.Match object; span=(2, 4), match='ㄱㅏ'>


#### sub

* 정규 표현식과 일치하는 부분을 다른 문자열로 교체

In [93]:
print(re.sub('[가-힣]', '가나다라마바사', '1'))
print(re.sub('[^가-힣]', '가나다라마바사', '1'))

1
가나다라마바사


### 토큰화(Tokenization)

* 한국어를 학습 데이터를 사용할 때는 언어의 특성으로 인해 추가로 고려해야 할 사항이 존재
* 한국어는 띄어쓰기를 준수하지 않아도 의미가 전달되는 경우가 많아 띄어쓰기가 지켜지지 않을 가능성이 존재
* 띄어쓰기가 지켜지지 않으면 정상적인 토큰 분리가 이루어지지 않음
* 한국어는 형태소라는 개념이 존재해 추가로 고려해주어야만 함
* '그는', '그가' 등의 단어들은 같은 의미를 가리키지만 텍스트 처리에서는 다르게 받아들일 수 있어 처리를 해줘야 함

#### 단어 토큰화

* 한국어는 공백으로 단어를 분리해도 조사, 접속사 등이 남아 분석에 어려움이 있음
* 이를 해결해주는 한국어 토큰화는 조사, 접속사를 분리해주거나 제거
* 한국어 토큰화를 사용하기 위해선 `konlpy`와 `mecab`이라는 라이브러리가 필요

In [2]:
from konlpy.tag import Mecab
tagger = Mecab(dicpath = r"C:/mecab/mecab-ko-dic")

In [5]:
sentence = '언제나 현재에 집중할 수 있다면 행복할것이다.'
tagger.pos(sentence)

[('언제나', 'MAG'),
 ('현재', 'NNG'),
 ('에', 'JKB'),
 ('집중', 'NNG'),
 ('할', 'XSV+ETM'),
 ('수', 'NNB'),
 ('있', 'VV'),
 ('다면', 'EC'),
 ('행복', 'NNG'),
 ('할', 'XSV+ETM'),
 ('것', 'NNB'),
 ('이', 'VCP'),
 ('다', 'EF'),
 ('.', 'SF')]

* 토큰화만 실행할 때는 `tagger.morphs()`라는 함수를 이용

In [6]:
tagger.morphs(sentence)

['언제나', '현재', '에', '집중', '할', '수', '있', '다면', '행복', '할', '것', '이', '다', '.']

* 형태소만 사용하고 싶을 때는 `tagger.nouns()`라는 함수를 이용해 조사, 접속사 등을 제거 가능

In [7]:
tagger.nouns(sentence)

['현재', '집중', '수', '행복', '것']

#### 문장 토큰화

* 한국어 문장을 토큰화할 때는 kss(korean sentence splitter) 라이브러리 이용

In [8]:
#!pip install kss

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
  Created wheel for kss: filename=kss-3.3.1.1-py3-none-any.whl size=42449239 sha256=23d5a6a5625f902b294b2a7f4565595f3c8dbccdc61eac89c393f5150ccaf856
  Stored in directory: C:\Users\User\AppData\Local\Temp\pip-ephem-wheel-cache-_1ps7yjx\wheels\02\b1\a4\6c41b81f6f42a8301b50c37e70842e20d00510fd0cf7f816ea
  Created wheel for emoji: filename=emoji-1.6.1-py3-none-any.whl size=169314 sha256=5829c834c88dadfc8bca6bf4f860bb34375116fa6d79bc3499b566bcc403ed48
  Stored in directory: C:\Users\User\AppData\Local\Temp\pip-ephem-wheel-cache-_1ps7yjx\wheels\04\29\50\1e7189f03d2cf139e469863d54a1d3eabeb10c92c84e51f8a1
Successfully built kss emoji


In [10]:
#!pip install regex

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


* 라이브러리를 이용해도 한국어에는 전치 표현이 존재해 제대로 토큰화가 안됨
* 좀 더 나은 학습을 위해 사용자는 해당 부분을 따로 처리해주어야만 함

In [12]:
import kss

text = '진짜? 내일 뭐하지. 이렇게 애매모호한 문장도? 밥은 먹었어? 나는...'
print(kss.split_sentences(text))

['진짜? 내일 뭐하지.', '이렇게 애매모호한 문장도? 밥은 먹었어?', '나는...']


#### 정규 표현식을 이용한 토큰화

* 한국어도 정규 표현식을 이용해 토큰화 가능

In [15]:
from nltk.tokenize import RegexpTokenizer

sentence = '안녕하세요 ㅋㅋ 저는 자연어 처리(Natural Language Processing)를ㄹㄹ!! 배우고 있습니다.'

tokenizer = RegexpTokenizer("[가-힣]+")
tokens = tokenizer.tokenize(sentence)
tokens

['안녕하세요', '저는', '자연어', '처리', '를', '배우고', '있습니다']

In [16]:
tokenizer = RegexpTokenizer("[ㄱ-ㅎ]+", gaps = True)
tokens = tokenizer.tokenize(sentence)
tokens

['안녕하세요 ', ' 저는 자연어 처리(Natural Language Processing)를', '!! 배우고 있습니다.']

#### 케라스를 이용한 토큰화


In [21]:
from keras.preprocessing.text import text_to_word_sequence

sentence = '성공의 비결은 단 한 가지, 잘할 수 있는 일에 광적으로 집중하는 것이다.'

text_to_word_sequence(sentence)

['성공의', '비결은', '단', '한', '가지', '잘할', '수', '있는', '일에', '광적으로', '집중하는', '것이다']

#### TextBlob을 이용한 토큰화

In [23]:
from textblob import TextBlob

blob = TextBlob(sentence)
blob.words

WordList(['성공의', '비결은', '단', '한', '가지', '잘할', '수', '있는', '일에', '광적으로', '집중하는', '것이다'])

## Bag of Words(BoW)

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ['Think like a man of action and act like man of thought.']

vector = CountVectorizer()
bow = vector.fit_transform(corpus)

print(bow.toarray())
print(vector.vocabulary_)

[[1 1 1 2 2 2 1 1]]
{'think': 6, 'like': 3, 'man': 4, 'of': 5, 'action': 1, 'and': 2, 'act': 0, 'thought': 7}


In [31]:
vector = CountVectorizer(stop_words = 'english')
bow = vector.fit_transform(corpus)

print(bow.toarray())
print(vector.vocabulary_)

[[1 1 2 2 1 1]]
{'think': 4, 'like': 2, 'man': 3, 'action': 1, 'act': 0, 'thought': 5}


In [33]:
corpus = ['평생 살 것처럼 꿈을 꾸어라. 그리고 내일 죽을 것처럼 오늘을 살아라.']

vector = CountVectorizer()
bow = vector.fit_transform(corpus)

print(bow.toarray())
print(vector.vocabulary_)

[[2 1 1 1 1 1 1 1 1]]
{'평생': 8, '것처럼': 0, '꿈을': 3, '꾸어라': 2, '그리고': 1, '내일': 4, '죽을': 7, '오늘을': 6, '살아라': 5}


In [35]:
import re
from konlpy.tag import Mecab
tagger = Mecab(dicpath = r"C:/mecab/mecab-ko-dic")

corpus = '평생 살 것처럼 꿈을 꾸어라. 그리고 내일 죽을 것처럼 오늘을 살아라.'
tokens = tagger.morphs(re.sub("(\.)", "", corpus))

vocab = {}
bow = []

for tok in tokens:
    if tok not in vocab.keys():
        vocab[tok] = len(vocab)
        bow.insert(len(vocab)-1, 1)
    else:
        index = vocab.get(tok)
        bow[index] = bow[index] + 1
        
print(bow)
print(vocab)

[1, 2, 2, 2, 1, 3, 1, 1, 1, 1, 1, 1, 1]
{'평생': 0, '살': 1, '것': 2, '처럼': 3, '꿈': 4, '을': 5, '꾸': 6, '어라': 7, '그리고': 8, '내일': 9, '죽': 10, '오늘': 11, '아라': 12}


## 문서 단어 행렬(DTM)

* 문서 단어 행렬(Document-Term Matrix)은 문서에 등장하는 여러 단어들의 빈도를 행렬로 표현
* 각 문서에 대한 BoW를 하나의 행렬로 표현한 것

In [36]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ["Think like a man of action and act like man of thought.",
         "Try not to become a man of success but rather try to become a man of value.",
         "Give me liberty, or give me death"]

vector = CountVectorizer(stop_words = 'english')
bow = vector.fit_transform(corpus)

print(bow.toarray())
print(vector.vocabulary_)

[[1 1 0 0 2 2 0 1 1 0 0]
 [0 0 0 0 0 2 1 0 0 2 1]
 [0 0 1 1 0 0 0 0 0 0 0]]
{'think': 7, 'like': 4, 'man': 5, 'action': 1, 'act': 0, 'thought': 8, 'try': 9, 'success': 6, 'value': 10, 'liberty': 3, 'death': 2}


In [37]:
import pandas as pd

columns = []
for k, v in sorted(vector.vocabulary_.items(), key = lambda item:item[1]):
    columns.append(k)

df = pd.DataFrame(bow.toarray(), columns = columns)
df

act  action  death  liberty  like  man  success  think  thought  try  value
0    1       1      0        0     2    2        0      1        1    0      0
1    0       0      0        0     0    2        1      0        0    2      1
2    0       0      1        1     0    0        0      0        0    0      0

## 어휘 빈도-문서 역빈도(TF-IDF) 분석

* 어휘 빈도-문서 역빈도(TF-IDF; Term Frequency-Inverse Docunment Frequency)는 단순히 빈도수가 높은 단어가 핵심어가 아닌, 특정 문서에서만 집중적으로 등장할 때 해당 단어가 문서의 주제를 잘 담고 있는 핵심어라고 가정
* 특정 문서에서 특정단어가 많이 등장하고 그 단어가 다른 문서에서 적게 등장할 때, 그 단어를 특정 문서의 핵심어로 간주
* 어휘 빈도-문서 역빈도는 어휘 빈도와 역문서 빈도를 곱해 계산 가능
* **어휘 빈도**는 특정 문서에서 특정 단어가 많이 등장하는 것을 의미

$$ tf_{x,y} $$

* **역문서 빈도**는 다른 문서에서 등장하지 않는 단어 빈도를 의미

$$ log(N/df_x) $$      

* **어휘 빈도-문서 역빈도**는 다음과 같이 표현

$$ W_{x,y} = tf_{x,y} * log(N/df_x) $$

* tf-idf를 편리하게 계산하기 위해 `scikit-learn`의 `tfidfvectorizer`를 이용
* 앞서 계산한 단어 빈도 수를 입력하여 tf-idf로 변환

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words = 'english').fit(corpus)

print(tfidf.transform(corpus).toarray())
print(tfidf.vocabulary_)

[[0.311383   0.311383   0.         0.         0.62276601 0.4736296
  0.         0.311383   0.311383   0.         0.        ]
 [0.         0.         0.         0.         0.         0.52753275
  0.34682109 0.         0.         0.69364217 0.34682109]
 [0.         0.         0.70710678 0.70710678 0.         0.
  0.         0.         0.         0.         0.        ]]
{'think': 7, 'like': 4, 'man': 5, 'action': 1, 'act': 0, 'thought': 8, 'try': 9, 'success': 6, 'value': 10, 'liberty': 3, 'death': 2}


* 좀 더 편리하게 확인하기 위해 데이터프레임으로 변환

In [39]:
columns = []
for k, v in sorted(tfidf.vocabulary_.items(), key = lambda item:item[1]):
    columns.append(k)

df = pd.DataFrame(tfidf.transform(corpus).toarray(), columns = columns)
df

act    action     death   liberty      like       man   success  \
0  0.311383  0.311383  0.000000  0.000000  0.622766  0.473630  0.000000   
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.527533  0.346821   
2  0.000000  0.000000  0.707107  0.707107  0.000000  0.000000  0.000000   

      think   thought       try     value  
0  0.311383  0.311383  0.000000  0.000000  
1  0.000000  0.000000  0.693642  0.346821  
2  0.000000  0.000000  0.000000  0.000000