# 텐서플로우 (Tensorflow)

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/TensorFlowLogo.svg/1200px-TensorFlowLogo.svg.png" width="300">

- 가장 널리 쓰이는 딥러닝 프레임워크 중 하나

- 구글이 주도적으로 개발하는 플랫폼

- 파이썬, C++ API를 기본적으로 제공하고,  
  자바스크립트(JavaScript), 자바(Java), 고(Go), 스위프트(Swift) 등 다양한 프로그래밍 언어를 지원

- tf.keras를 중심으로 고수준 API 통합 (2.x 버전)

- TPU(Tensor Processing Unit) 지원
  - TPU는 GPU보다 전력을 적게 소모, 경제적
  
  - 일반적으로 32비트(float32)로 수행되는 곱셈 연산을 16비트(float16)로 낮춤

## 텐서플로우 아키텍쳐

<img src="https://developers.google.com/machine-learning/crash-course/images/TFHierarchy.svg">

<sub>출처: https://developers.google.com/machine-learning/crash-course/first-steps-with-tensorflow/toolkit</sub>

## 텐서플로우 시작하기

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
print(tf.__version__)

2.6.0


### 텐서(Tensor)의 객체
- 타입(Type): `string`, `float32`, `float16`, `int32`, `int8` 등

- 형상(Shape): 0, 1, 2차원 등의 데이터 차원 

- 축(Rank): 차원의 개수

### 텐서의 차원과 연산

In [3]:
a = tf.constant(2)
print(tf.rank(a))
print(a)

## Rank > 0차원

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [4]:
b = tf.constant([2, 3])
print(tf.rank(b))
print(b)

## Rank > 1차원
## 1차원 형태에 개수는 두개 == (2, )

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [5]:
c = tf.constant([[2, 3], [6, 7]])
print(tf.rank(c))
print(c)

## Rank > 2차원
## 2차원 형태에 개수는 두개 == (2, 2)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [6]:
# String 형태
d = tf.constant(['Hello'])
print(tf.rank(d))
print(d)

## Rank > 1
## shape = (1, ), 1차원 tensor에 값 하나만 들어감
## dtype = string

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'Hello'], shape=(1,), dtype=string)


### 난수 생성

In [7]:
rand = tf.random.uniform([1], 0, 1)
print(rand.shape)
print(rand)

## 0과 1사이의 랜덤값 생성 : MinMax(0, 1)

(1,)
tf.Tensor([0.38198483], shape=(1,), dtype=float32)


In [8]:
# 정규분포형태의 랜덤값
rand2 = tf.random.normal([1, 2], 0, 1)
print(rand2.shape)
print(rand2)

## mean : 0.0  /  standard_deviation : 1.0 
## 음수 / 양수 같이 출력될 수 있음

(1, 2)
tf.Tensor([[0.59504    0.24252123]], shape=(1, 2), dtype=float32)


In [9]:
rand3 = tf.random.normal(shape = (3, 2), mean = 0.0, stddev = 1.0)
print(rand3.shape)
print(rand3)

## 3 by 2 => (3, 2)짜리 정규분포를 따르는 난수 생성

(3, 2)
tf.Tensor(
[[-0.5845134  -0.57164544]
 [ 0.88314366  0.9090248 ]
 [ 0.47317633 -0.7937704 ]], shape=(3, 2), dtype=float32)


### 즉시 실행 모드 (Eager Mode) 지원
- 즉시 실행모드를 통해 텐서플로우를 파이썬처럼 사용할 수 있음

- 1.x 버전에서는 '그래프'를 생성하고, 초기화 한 뒤에 세션을 통해 **값을 흐르게 하는 작업**을 진행해야함


In [10]:
a = tf.constant(3)
b = tf.constant(2)

In [11]:
print(tf.add(a, b))   #  'add' Method
print(a + b)          #  'plus' Operator

## Numpy와 유사하게 동작

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [12]:
print(tf.subtract(a, b))
print(a - b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [13]:
print(tf.multiply(a, b))
print(a * b)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


### 텐서 플로우 ↔ 넘파이
- `numpy()`
- `tf.convet_to_tensor()`

In [14]:
c = tf.add(a, b).numpy()
print(type(c))

## 계산 결과를 numpy형태로 return

<class 'numpy.int32'>


In [15]:
c_square = np.square(c, dtype = np.float32)
c_tensor = tf.convert_to_tensor(c_square)

print(c_tensor)
print(type(c_tensor))

## c_tensro : 'tensorflow.python.framework.ops.EagerTensor' EagerTensor 타입

tf.Tensor(25.0, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


### 넘파이처럼 사용하기


In [16]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.,]])

print(t.shape)
print(t.dtype)

## shape (2, 3) / dtype = float32
## 실수형태로 넣었기에 자동으로 float32형태로 출력

(2, 3)
<dtype: 'float32'>


In [17]:
# Slicing

print(t[:, 1:])

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [18]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [19]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [20]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [22]:
t @ tf.transpose(t)

## 2,3 * 3,2 => 2,2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

### 타입 변환
- 텐서의 기본 dtype
  - float형 텐서: `float32`
  - int형 텐서: `int32`

- 연산시 텐서의 타입을 맞춰줘야 함
  - `float32` ~ `float32`
  - `int32` ~ `int32`
  - `flot32` ~ `int32` (x)

- 타입변환에는 `tf.cast()` 사용

In [23]:
a = tf.constant(2)
print(a)

b = tf.constant(2.)
print(b)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [24]:
tf.constant(2.) + tf.constant(40)

## 두개의 데이터타입이 다르기때문에 에러값출력

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

In [25]:
tf.constant(2.) + tf.constant(30., dtype = tf.float64)

## 똑같은 float이라도 타입이 다르면 계산 불가

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]

In [28]:
t = tf.constant(30., dtype = tf.float64)
t2 = tf.constant(4.)    # float32

print(t2 + tf.cast(t, tf.float32))

tf.Tensor(34.0, shape=(), dtype=float32)


### AutoGraph (오토그래프)

- Tensorflow가 작업을 좀 더 빠르게 동작하게 하기 위한 방법으로 Graph로 만들어 연산을 진행

- `tf.Graph`

- 유연성이 있음

  - 모바일 애플리케이션, 임베디드 기기, 백엔드 서버와 같이 Python 인터프리터가 없는 환경에서 Tensorflow 사용 가능 

In [29]:
import timeit

### @tf.function
- 자동으로 그래프를 생성(Auto Graph)

- 그래프로 변환하여 사용 -> GPU 연산 가능

- 파이썬으로 구성된 함수를 텐서플로우의 그래프 형태로 다루고 싶을 때 사용가능


- 원본 함수가 필요하다면 `(tf.function).python_function()`

In [30]:
@tf.function
def my_function(x):
    return x**2 - 10*x + 3

print(my_function(2))
print(my_function(tf.constant(2)))

tf.Tensor(-13, shape=(), dtype=int32)
tf.Tensor(-13, shape=(), dtype=int32)


In [31]:
def my_function_(x):
    return x**2 - 10*x + 3

print(my_function_(2))
print(my_function_(tf.constant(2)))

-13
tf.Tensor(-13, shape=(), dtype=int32)


In [32]:
tf_my_func = tf.function(my_function_)

print(tf_my_func)
print(tf_my_func(2))

tf.Tensor(-13, shape=(), dtype=int32)


In [33]:
tf_my_func.python_function(2)

-13

In [34]:
def function_to_get_faster(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

a_function_that_uses_a_graph = tf.function(function_to_get_faster)

# 다양한 tensor 삽입 후, 결과
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

a_function_that_uses_a_graph(x1, y1, b1).numpy()

array([[12.]], dtype=float32)

In [36]:
# python함수와 tensorlor함수를 혼합하여 사용 가능
def inner_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

@tf.function
def outer_function(x):
    y = tf.constant([[2.0], [3.0]])
    b = tf.constant(4.0)
    return inner_function(x, y, b)

outer_function(tf.constant([[1.0, 2.0]])).numpy()

array([[12.]], dtype=float32)

텐서플로우가 `tf.function`으로 변환한 코드

In [38]:
print(tf.autograph.to_code(my_function.python_function))
print(tf.autograph.to_code(tf_my_func.python_function))
print(tf.autograph.to_code(outer_function.python_function))

def tf__my_function(x):
    with ag__.FunctionScope('my_function', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = (((ag__.ld(x) ** 2) - (10 * ag__.ld(x))) + 3)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)

def tf__my_function_(x):
    with ag__.FunctionScope('my_function_', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = (((ag__.ld(x) ** 2) - (10 * ag__.ld(x))) + 3)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)

def 


 속도 향상


In [41]:
class SequentialModel(tf.keras.Model):
    def __init__(self, **kwargs):
        super(SequentialModel, self).__init__(**kwargs)
        self.flatten = tf.keras.layers.Flatten(input_shape = (28, 28))
        self.dense_1 = tf.keras.layers.Dense(128, activation = 'relu')
        self.dropout = tf.keras.layers.Dropout(0.2)
        self.dense_2 = tf.keras.layers.Dense(10)
        
    def call(self, x):
        x = self.flatten(x)
        x = self.dense_1(x)
        x = self.dropout(x)
        x = self.dense_2(x)
        return x
    
input_data = tf.random.uniform([60, 28, 28])

eager_model = SequentialModel()
graph_model = tf.function(eager_model)

print("Eager time:", timeit.timeit(lambda: eager_model(input_data), number = 10000))
print("Graph time:", timeit.timeit(lambda: graph_model(input_data), number = 10000))

Eager time: 7.5528746999998475
Graph time: 3.644989300000134


### 변수 생성

- `tf.Variable`
- 딥러닝 모델 학습 시, 그래프 연산이 필요할 때 사용

In [42]:
X = tf.Variable(20.0)

print(X)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=20.0>


### Autograd (자동 미분)

- `tf.GradientTape` API를 사용
- `tf.Variable` 같은 일부 입력에 대한 기울기 계산
  - 기본적으로 한번만 사용됨
- 변수가 포함된 연산만 기록

In [44]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x**2

In [45]:
dy_dx = tape.gradient(y, x)
dy_dx.numpy()

6.0

In [47]:
#x2 = tf.Variable(4)
#dy_dx = tape.gradient(y, x2)
#dy_dx.numpy()

In [49]:
x = tf.Variable(2.0)
y = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y_sq = y**2
    z = x**2 + tf.stop_gradient(y_sq)
    
grad = tape.gradient(z, {'x':x, 'y':y})

print('dz/dx:', grad['x'])

print('dz/dy:', grad['y'])

dz/dx: tf.Tensor(4.0, shape=(), dtype=float32)
dz/dy: None


In [52]:
weights = tf.Variable(tf.random.normal((3, 2)), name = 'weights')
biases = tf.Variable(tf.zeros(2, dtype = tf.float32), name = 'biases')
x = [[1., 2., 3.]]

with tf.GradientTape(persistent = True) as tape:
    y = x @ weights + biases
    loss = tf.reduce_mean(y**2)

In [54]:
[dl_dw, dl_db] = tape.gradient(loss, [weights, biases])

In [55]:
print(weights.shape)
print(dl_dw.shape)

(3, 2)
(3, 2)


In [59]:
wegiths2 = tf.Variable(tf.random.normal((3, 2)), name = 'weights')
biases2 = tf.Variable(tf.zeros(2, dtype = tf.float32), name = 'biases')
x = [[4., 5., 6.]]

[dl_dw2, dl_db2] = tape.gradient(loss, [wegiths2, biases2])

print(wegiths2.shape)
print(dl_dw.shape)

(3, 2)
(3, 2)


In [60]:
del tape

## 간단한 신경망 구조 

### 뉴런
- 입력 → 연산 → 활성화함수 → 출력

In [61]:
def sigmoid(x):
    return (1 / (1 + np.exp(-x)))

def Neuron(x, W, bias = 0):
    z = x * W + bias
    return sigmoid(z)

In [63]:
x = tf.random.normal((1, 2), 0, 1)    # 차례대로 shape, mean, deviation값 지정
W = tf.random.normal((1, 2), 0, 1)

print('x.shape:', x.shape)
print('W.shape:', W.shape)

print(x)
print(W)

print(Neuron(x, W))

x.shape: (1, 2)
W.shape: (1, 2)
tf.Tensor([[1.440025  1.9961505]], shape=(1, 2), dtype=float32)
tf.Tensor([[-0.4583562  1.1826849]], shape=(1, 2), dtype=float32)
[[0.34072962 0.9137902 ]]


In [64]:
x = tf.random.normal((2, 1), 0, 1)
W = tf.random.normal((2, 1), 0, 1)

print('x.shape:', x.shape)
print('W.shape:', W.shape)

print(x)
print(W)

print(Neuron(x, W))

x.shape: (2, 1)
W.shape: (2, 1)
tf.Tensor(
[[-0.7704724 ]
 [ 0.11450391]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[-0.4934482]
 [-2.2989357]], shape=(2, 1), dtype=float32)
[[0.5939185 ]
 [0.43456814]]


In [65]:
x = tf.random.normal((1,), 0, 1)
W = tf.random.normal((2, 1), 0, 1)

print('x.shape:', x.shape)
print('W.shape:', W.shape)

print(x)
print(W)

print(Neuron(x, W))

x.shape: (1,)
W.shape: (2, 1)
tf.Tensor([-1.9822352], shape=(1,), dtype=float32)
tf.Tensor(
[[-0.24350224]
 [-0.7220018 ]], shape=(2, 1), dtype=float32)
[[0.6183802]
 [0.8070847]]


### 퍼셉트론 학습 알고리즘 (가중치 업데이트)

## $\qquad w^{(next step)} = w + \eta \ (y - \tilde{y}) \ x$

- $w \ $: 가중치

- $\eta \ $ : 학습률

- $y \ $ : 정답 레이블

- $\tilde{y} \ $: 예측 레이블

- 가중치가 계속해서 업데이트되는 구성


In [66]:
x = 1
y = 0
W = tf.random.normal([1], 0, 1)
print(Neuron(x, W))
print('y:', y)

[0.7160376]
y: 0


In [67]:
for i in range(1000):
    output = Neuron(x, W)
    error = y - output
    # 가중치(W) 업데이트
    W = W + x * 0.1 * error
    
    if i % 100 == 99:
        print("{}\t{}\t{}".format(i+1, error, output))

100	[-0.11829542]	[0.11829542]
200	[-0.05654635]	[0.05654635]
300	[-0.03669327]	[0.03669327]
400	[-0.02706086]	[0.02706086]
500	[-0.0214018]	[0.0214018]
600	[-0.01768657]	[0.01768657]
700	[-0.01506365]	[0.01506365]
800	[-0.01311452]	[0.01311452]
900	[-0.01160979]	[0.01160979]
1000	[-0.01041343]	[0.01041343]


In [71]:
def Neuron2(x, W, bias = 0):
    z = tf.matmul(x, W, transpose_b = True) + bias
    return sigmoid(z)

In [72]:
x = tf.random.normal((1, 3), 0, 1)
y = tf.ones(1)
W = tf.random.normal((1, 3), 0, 1)

print(Neuron2(x, W))
print('y:', y)

## (1, 3) matmul (3, 1) ==> (1, 1)
## transpose_b = True :  (1, 3) >>> (3, 1)

[[0.73229367]]
y: tf.Tensor([1.], shape=(1,), dtype=float32)


In [73]:
for i in range(1000):
    output = Neuron2(x, W)
    error = y - output
    W = W + x * 0.1 * error
    
    if i % 100 == 99:
        print("{}\t{}\t{}".format(i+1, error, output))

100	[[0.01777476]]	[[0.98222524]]
200	[[0.00900245]]	[[0.99099755]]
300	[[0.00602007]]	[[0.99397993]]
400	[[0.0045203]]	[[0.9954797]]
500	[[0.00361812]]	[[0.9963819]]
600	[[0.00301594]]	[[0.99698406]]
700	[[0.00258541]]	[[0.9974146]]
800	[[0.00226235]]	[[0.99773765]]
900	[[0.00201106]]	[[0.99798894]]
1000	[[0.00181001]]	[[0.99819]]


In [74]:
# 가중치 추가해서 만들기
x = tf.random.normal((1, 3), 0, 1)
weights = tf.random.normal((1, 3), 0, 1)
bias = tf.zeros((1, 1))

y = tf.ones((1, ))

print('x\t: {}\nweights\t: {}\nbias\t: {}'.format(x, weights, bias))

x	: [[-0.59255105  1.2478535  -0.3396848 ]]
weights	: [[ 1.3007523  -1.0083337   0.91446364]]
bias	: [[0.]]


### AND Gate

### OR Gate

### XOR Gate

## 시각화 사용

### XOR Gate의 'LOSS' 시각화
